/**
 * ARAYÜZ dili — belge dilinden (`scriptLang`) AYRI bir eksen.
 *
 * Kullanıcı kararı (2026-08-27): program varsayılan İNGİLİZCE açılır,
 * Ayarlar'dan değiştirilir. Belge dili senaryonun terimlerini (İÇ./INT.)
 * yönetir ve dokümanla gezer; arayüz dili yalnız bu makinenin tercihi.
 *
 * ## Tasarım — Türkçe dizgi ANAHTARDIR
 *
 * `t('Kaydet')` → dil İngilizce ise sözlükten 'Save', değilse (ya da
 * anahtar sözlükte yoksa) Türkçe'nin kendisi döner. Anahtar-kimlik icat
 * edilmedi: 200+ mevcut dizgiyi `save_button` gibi kimliklere taşımak her
 * çağrı yerini iki kez değiştirmek olurdu; bu yolla sarmak tek dokunuş ve
 * ÇEVRİLMEMİŞ dizgi sessizce kaybolmaz, Türkçe görünür — eksik çeviri
 * görünür bir iştir, kırık bir arayüz değil.
 *
 * ## Tepkisellik — kök yeniden kurulur
 *
 * `t` modül değişkenini okur, React'e abone değildir. Dil değişimi nadir
 * bir ayar eylemidir: kabuk kökü `key={arayuzDili}` taşır ve değişimde
 * ağaç yeniden kurulur. Her bileşene ayrı abonelik dağıtmak 60 dosyada
 * ikinci bir kablo olurdu.
 */

export type ArayuzDili = 'en' | 'tr';

export const VARSAYILAN_ARAYUZ_DILI: ArayuzDili = 'en';

const ANAHTAR = 'mizansen.arayuz-dili';

/** `localStorage` bazı bağlamlarda erişimde FIRLATIR (gizli pencere) — korumalı. */
export function arayuzDiliOku(): ArayuzDili {
  try {
    const ham = globalThis.localStorage?.getItem(ANAHTAR);
    return ham === 'tr' || ham === 'en' ? ham : VARSAYILAN_ARAYUZ_DILI;
  } catch {
    return VARSAYILAN_ARAYUZ_DILI;
  }
}

let aktif: ArayuzDili = arayuzDiliOku();

/* AÇILIŞTA `<html lang>` dile eşitlenir. index.html'de sabit `tr` yazıyor
   ve CSS `text-transform: uppercase` dili oradan okuyor: İngilizce
   arayüzde "LIBRARY" → "LİBRARY" oluyordu, çünkü Türkçe'de `i`nin büyüğü
   `İ`dir. Dil DEĞİŞİMİNDE aynı işi `store/ui.ts` yapıyor. */
try { globalThis.document?.documentElement?.setAttribute('lang', aktif); } catch { /* DOM yok */ }

export function arayuzDili(): ArayuzDili {
  return aktif;
}

export function arayuzDiliniAyarla(dil: ArayuzDili): void {
  aktif = dil;
  try {
    globalThis.localStorage?.setItem(ANAHTAR, dil);
  } catch {
    /* kalıcılık yoksa oturumluk tercih yine geçerli */
  }
}

/** Testler için — modül durumu testler arasında taşınmasın. */
export function arayuzDiliniSifirla(): void {
  aktif = VARSAYILAN_ARAYUZ_DILI;
}

/**
 * Çevirir. Bilinmeyen anahtar TÜRKÇE döner — sessiz kayıp yok, eksik
 * çeviri ekranda Türkçe olarak görünür ve `eksikCeviriler()` ile ölçülür.
 */
export function t(tr: string): string {
  if (aktif === 'tr') return tr;
  return EN[tr] ?? tr;
}

/** Biçimli çeviri: `tf('%d görsel bulunamadı', 3)`. */
export function tf(tr: string, ...degerler: (string | number)[]): string {
  let metin = t(tr);
  for (const d of degerler) metin = metin.replace(/%[ds]/, String(d));
  return metin;
}

/* ------------------------------------------------------------------ */
/* SÖZLÜK — tr → en. Bölümler kaynak dosyaya göre; alfabetik değil,     */
/* bulunabilirlik dosya komşuluğundan geliyor.                          */
/* ------------------------------------------------------------------ */

export const EN: Record<string, string> = {
  "Yapım": "Production",
  "Efekt": "Effects",
  'Filigran': 'Watermark',
  "Masa": "Table",
  "Sandalye": "Chair",
  "Koltuk": "Sofa",
  "Yatak": "Bed",
  "Dolap": "Cabinet",
  "Kutu": "Box",
  "Pencere": "Window",
  "Merdiven": "Stairs",
  "Duvar": "Wall",
  "Araba (Yan)": "Car (Side)",
  "Araba (Ön)": "Car (Front)",
  "Bisiklet": "Bicycle",
  "Otobüs": "Bus",
  "Dağ": "Mountain",
  "Bulut": "Cloud",
  "Güneş": "Sun",
  "Telefon": "Phone",
  "Dizüstü": "Laptop",
  "Kitap": "Book",
  "Bardak": "Cup",
  "Tabanca": "Pistol",
  "Çanta": "Bag",
  "Sandık": "Chest",
  "Patlama": "Explosion",
  "Hız Çizgileri": "Speed Lines",
  "Konuşma Balonu": "Speech Bubble",
  "Düşünce Balonu": "Thought Bubble",
  "Işık Huzmesi": "Light Beam",
  "Amerikan": "American",
  "Fransız": "French",
  "Bu rol dışa aktaramaz.": "This role cannot export.",
  /* ---- genel / Modal ---- */
  'Analiz panosu…': 'Analysis board…',
  'ekranda hep görünür; çıktıda varsayılan olarak yok': 'always visible on screen; absent from the output by default',
  'hiç işaret yok — çıktı boş olur': 'no marks — the output will be empty',
  'hiç işaret yok — sayfalar renksiz basılır': 'no marks — pages will print without revision colour',
  'işaretli satır': 'marked lines',
  'İkisi': 'Both',
  'Kapat': 'Close',
  'Revizyon basımı iki sütunlu belgeye uygulanmadı — sayfalar beyaz basıldı.': 'Revision printing was not applied to the two-column document — pages printed white.',
  'Revizyon olarak bas': 'Print as revision',
  'Revizyon': 'Revision',
  'Revizyon yayınla': 'Publish revision',
  'Revizyon yok': 'No revision',
  'Revizyon rengi': 'Revision colour',
  'Beyaz': 'White',
  'Mavi': 'Blue',
  'Pembe': 'Pink',
  'Sarı': 'Yellow',
  'Yeşil': 'Green',
  'Altın Sarısı': 'Goldenrod',
  'Devetüyü (Buff)': 'Buff',
  'Somon': 'Salmon',
  'Kiraz': 'Cherry',
  'Açık Kahverengi (Tan)': 'Tan',
  'Revizyon yok — renkli sayfa basmak için önce bir revizyon açın.': 'No revision — open a revision first to print coloured pages.',
  'revizyonu açıldı': 'revision opened',
  'Seçimi işaretle': 'Mark selection',
  'Seçimin revizyon işaretini kaldır': 'Unmark selection',
  'Sütun ayıracını bas': 'Print the column divider',
  'Vazgeç': 'Cancel',
  'Kaydet': 'Save',
  'Sil': 'Delete',
  'Ekle': 'Add',
  'Kaldır': 'Remove',
  'Aç': 'Open',
  'Evet': 'Yes',
  'Hayır': 'No',
  'Tamam': 'OK',

  /* ---- Ayarlar ---- */
  'Ayarlar': 'Settings',
  'Arayüz dili': 'Interface language',
  'Türkçe': 'Türkçe',
  'English': 'English',
  'Dil değişikliği için pencere yeniden çizilir.': 'The window is redrawn when the language changes.',
/* ---- Toolbar ---- */
  'Senaryo': 'Screenplay',
  'Kartlar': 'Cards',
  'Kart filtreleri': 'Card filters',
  'Galeri': 'Gallery',
  'Kalem': 'Pen',
  'Fırça': 'Brush',
  'Silgi': 'Eraser',
  'Dikdörtgen': 'Rectangle',
  'Elips': 'Ellipse',
  'Yalnız işaretli sayfalar': 'Marked pages only',
  'Çizgi': 'Line',
  'Çokgen': 'Polygon',
  /* ASCII-only ve interpolasyonla bölünmüş kaçaklar — tarayıcı 2026-08-31'de
     daraltılınca görünür oldu (bkz. i18n-kapsam.test.ts). */
  /* Kütüphane kategorileri (`data/cameras.ts`, `data/props.ts`) — tablo
     Türkçe, karşılık burada. */
  /* Dünya türleri (`DunyalarSekmesi`) — tablo hiç sarılmamıştı. */
  'Mekân': 'Place',
  'Kurum': 'Institution',
  'Kavram': 'Concept',
  'Olay': 'Event',
  'Konum': 'Position',
  'Hareket': 'Movement',
  'Mobilya': 'Furniture',
  'Nesne': 'Object',
  'Doğa': 'Nature',
  /* Karşılaştırma etiketleri. */
  'yeni': 'new',
  'silindi': 'deleted',
  /* ÇOK SATIRLI JSX kaçakları — tarayıcının üçüncü kör noktası
     (ajan taraması 2026-08-31). `Sil` ve `Kurtar` sözlükte ZATEN vardı ama
     uygulanmamıştı: İngilizce arayüzde panel silme düğmesi "Sil" yazıyordu. */
  'Presetler Amerikan formatın aynısı; hangi sütuna düşeceğini preset belirler — aksiyon ve geçiş sola, karakter/parantez/diyalog sağa.':
    'The presets match the American format; the preset decides which column a line lands in — action and transition on the left, character/parenthetical/dialogue on the right.',
  'Temizle': 'Clear',
  'Geri getir': 'Restore',
  'Oturumu kapat': 'End session',
  'Hedef dil': 'Target language',
  'Koyuluk': 'Darkness',
  'Tek PDF: önce senaryo, arkasında storyboard panelleri. Senaryo sayfaları editördekiyle aynı sayıda kalır.':
    'One PDF: screenplay first, storyboard panels behind it. The screenplay keeps the same page count as in the editor.',
  'Girdiler tek bir akışta iner: bir sonraki satır, öncekinin bittiği yerden başlar. Solda dört satırlık bir olay varsa ardından gelen diyalog sağda beşinci satırdan başlar.':
    'Entries flow in a single stream: each line starts where the previous one ended. If an action on the left runs four lines, the dialogue that follows starts on the fifth line on the right.',
  'Bu sürümde yazım denetimi yok — eklediğin kelimeler projeyle birlikte saklanır ve masaüstü uygulamasında etkili olur.':
    'There is no spellcheck in this build — the words you add are stored with the project and take effect in the desktop app.',
  '↑↓ gez · ⏎ panel oluştur · ⇧⏎ panele bağla · Space çizimi aç · Del bağlantıyı kaldır · sağ tık menüsü':
    '↑↓ navigate · ⏎ create panel · ⇧⏎ link to panel · Space open drawing · Del unlink · right-click menu',
  'Objeler': 'Objects',
  'uygulanır: bir parça bile eksik dönerse belgeye hiçbir şey yazılmaz. Sahne başlıklarının terimleri (İÇ/DIŞ) makineye gönderilmez, hedef dilde yeniden kurulur.':
    'applies: if even one piece comes back missing, nothing is written to the document. Scene heading terms (INT/EXT) are not sent to the machine; they are rebuilt in the target language.',
  'Metin': 'Text',
  'Kova doldurma': 'Fill bucket',
  'Kement seçim': 'Lasso select',
  'Damlalık': 'Eyedropper',
  'Kaydır': 'Pan',
  'Ortak çalışma oturumu': 'Collaboration session',
  'Ortak çalışmada senin rengin': 'Your color in collaboration',
  'Odak modu (F) — yalnız senaryo görünümünde': 'Focus mode (F) — screenplay view only',
  'Odak modu': 'Focus mode',
  'Sunum modu — panelleri tam ekran sırayla göster': 'Presentation mode — show panels fullscreen in order',
  'Sunum': 'Present',
  'Kaydet (Ctrl+S)': 'Save (Ctrl+S)',
  'Dışa aktar': 'Export',
  'Kütüphane (figür, poz, obje, şablon)': 'Library (figures, poses, objects, templates)',
  'Kontur rengi': 'Stroke color',
  'Fırça boyutu ( [ / ] )': 'Brush size ( [ / ] )',
  'Kağıt': 'Paper',
  'Dil': 'Language',
  'Uygulama menüsü': 'Application menu',
  'Satır preseti': 'Line preset',
  'Senaryo yazı tipi Courier’dir; sektör konvansiyonu ve sayfa sayısı buna bağlı.':
    'The screenplay typeface is Courier; the industry convention and the page count depend on it.',
  'Punto 12’dir: satır başına 60 karakter, sayfa başına 55 satır. Değişirse sayfa ≈ dakika sözleşmesi çöker.':
    'The size is 12pt: 60 characters per line, 55 lines per page. Change it and the page ≈ minute contract collapses.',
  'Satır aralığı ızgaranın kendisidir (6 satır/inç); değişirse sayfa sayısı yalancı çıkar.':
    'Line spacing is the grid itself (6 lines/inch); change it and the page count lies.',
  /* Kısayol listesinden — dokuzu `t()` ile sarılmamıştı ve İngilizce
     arayüzde Türkçe basılıyordu (gerçek Electron penceresinde görüldü,
     2026-08-30). Kaynak tarayıcısı bunları görmüyordu: dizi elemanı
     olarak duruyorlar, JSX metni değiller. */
  'Ok': 'Arrow',
  'Yeni panel': 'New panel',
  'Shift + tekerlek': 'Shift + wheel',
  'Senaryo gezgini': 'Screenplay navigator',
  'Yazarken': 'While writing',
  'Odak modu (yan panelleri gizle)': 'Focus mode (hide side panels)',
  'Bu listeyi aç (yalnız pano — soru işareti bir karakterdir)':
    'Open this list (board only — the question mark is a character)',
  'Seçili satırları revizyonda işaretle': 'Mark the selected lines in the revision',
  'Yeni revizyon turu yayınla': 'Publish a new revision round',
  'geri almak için Ctrl+Z': 'Ctrl+Z to undo',
  'Yer imi rengini değiştir': 'Change bookmark colour',
  'tıkla: renk, sağ tık: kaldır': 'click: colour, right-click: remove',
  'etiketsiz': 'unlabelled',
  /* İNTERPOLASYONLA BÖLÜNMÜŞ metinler — tarayıcının dördüncü kör noktası.
     `{sayı} satır`, `Çıktı: {w}×{h}` gibi metinlerde JSX metin düğümü
     `{...}` içeriyor ve tarayıcı `[^<>{}]` ile arıyordu, yani hepsini
     atlıyordu. Kullanıcı gerçek pencerede gördü (2026-08-30). */
  'obje': 'objects',
  'satır': 'lines',
  'Aktif kullanıcılar': 'Active users',
  'Oynat': 'Play',
  'Duraklat': 'Pause',
  'Çıktı': 'Output',
  'Değişkenler': 'Variables',
  'örn.': 'e.g.',
  'Henüz sahne yok.': 'No scenes yet.',
  'Adsız senaryo': 'Untitled screenplay',
  'SAYFA BAŞI': 'PAGE BREAK',
  'Sayfa başı koy / kaldır — bu satır yeni sayfada başlar':
    'Insert / remove page break — this line starts a new page',
  'İmleçteki satırın preseti — Ctrl+1..9 ile de seçilir': "Preset of the line at the cursor — also via Ctrl+1..9",
  'Yazı tipi': 'Typeface',
  'Belgenin yazı tipi — sayfa sayısı buna bağlı': "Document typeface — page count depends on it",
  'Yeni proje': 'New project',
  'Aç…': 'Open…',
  'Son açılanlar…': 'Recent…',
  'Farklı kaydet…': 'Save as…',
  'Dışa aktar…': 'Export…',
  'Başlık sayfası…': 'Title page…',
  'Sürüm geçmişi…': 'Version history…',
  'Sürümleri karşılaştır…': 'Compare versions…',
  'Senaryoyu çevir…': 'Translate screenplay…',
  'Ortak çalışma oturumu…': 'Collaboration session…',
  'Klavye kısayolları': 'Keyboard shortcuts',
  'Adsız': 'Untitled',
  'Oturum': 'Session',

  /* ---- otomatik süpürme (2026-08-27) ---- */
  '%100\'e dön': 'Back to 100%',
  '1. taslak, 2026-08-26…': '1st draft, 2026-08-26…',
  'Ad': 'Name',
  'Adınız': 'Your name',
  'Aksiyon': 'Action',
  'Aksiyon güvenli': 'Action safe',
  'Almanca': 'German',
  'Alta diyalog ekle': 'Add dialogue below',
  'Alta olay ekle': 'Add event below',
  'Alıcının adı ya da TASLAK': 'Recipient name or DRAFT',
  'Analiz': 'Analysis',
  'Animatik oluştur': 'Create animatic',
  'Animatik video': 'Animatic video',
  'Animatik önizleme': 'Animatic preview',
  'Ara': 'Search',
  'Araçlar (pano)': 'Tools (board)',
  'Açı': 'Angle',
  'Açıklama': 'Description',
  'Açılamadı': 'Could not open',
  'Açıldı': 'Opened',
  'Bağlantı kaldırıldı.': 'Link removed.',
  'Bağlantı koptu — çevrimdışı düzenlemeler bağlanınca birleşecek': 'Connection lost — offline edits will merge when reconnected',
  'Bağlantıyı kaç kişi kullanabilir': 'How many people can use this link',
  'Bağlanılıyor…': 'Connecting…',
  'Bağlı': 'Linked',
  'Bağsız': 'Unlinked',
  'Bağı kaldır': 'Remove link',
  'Başa sar': 'Rewind',
  'Başlık Sayfası': 'Title Page',
  'Başlık güvenli': 'Title safe',
  'Başlık sayfası ekle': 'Add title page',
  'Belgenin biçimi': 'Document format',
  'Biçim': 'Format',
  'Blok preseti': 'Block preset',
  'Boy': 'Height',
  'Bu adda bir proje yok.': 'No project with this name.',
  'Bu katmana çiz': 'Draw on this layer',
  'Bu link farklı bir sunucu adresi içeriyor. Adresi kontrol edip katılmayı elle onaylayın.': 'This link contains a different server address. Check the address and confirm joining manually.',
  'Bu oturumda düzenleme izniniz yok.': 'You don\'t have edit permission in this session.',
  'Bu oturumda çökme koruması yok — yazdıkların diske günlüklenmiyor.': 'No crash protection in this session — your writing is not journaled to disk.',
  'Bu projede henüz panel yok.': 'This project has no panels yet.',
  'Bu roldeki kullanıcılar dışa aktarma yapamaz. Yalnızca': 'Users with this role cannot export. Only the',
  'Bu satırı sil': 'Delete this line',
  'Bu sürüme dönülsün mü? Kaydedilmemiş değişiklikler kaybolur.': 'Restore this version? Unsaved changes will be lost.',
  'Bu sürüme dönülsün mü? Mevcut durum önce bir kontrol noktasına yazılacak.': 'Restore this version? The current state will first be saved as a checkpoint.',
  'Davet linkindeki token': 'Token from the invite link',
  'Davet oluştur': 'Create invite',
  'Davet token’ı': 'Invite token',
  'Dikey aynala': 'Flip vertically',
  'Diyalog': 'Dialogue',
  'Dosya adı şablonu': 'Filename template',
  'Döküm': 'Breakdown',
  'Döndür X': 'Rotate X',
  'Döndür Y': 'Rotate Y',
  'Döndür Z': 'Rotate Z',
  'Döndürme': 'Rotation',
  'Dönüş': 'Turn',
  'Dünya': 'World',
  'Düz metin': 'Plain text',
  'Düz metin (.txt)': 'Plain text (.txt)',
  'Düz metin — panel görselleri taşınmaz.': 'Plain text — panel images are not included.',
  'Düzenleme': 'Editing',
  'Dışa Aktar': 'Export',
  'Dışa aktarma iptal edildi.': 'Export cancelled.',
  'En-boy': 'Aspect ratio',
  'Etiket': 'Label',
  'Eğim': 'Tilt',
  'Farkı gör': 'See the difference',
  'Final Draft senaryosu': 'Final Draft screenplay',
  'Fountain metni': 'Fountain text',
  'Fransızca': 'French',
  'Fırça boyutunu küçült / büyüt': 'Decrease / increase brush size',
  'Genişlik': 'Width',
  'Geri al': 'Undo',
  'Geri al (Ctrl+Z)': 'Undo (Ctrl+Z)',
  'planlar': 'shots',
  'seçili': 'selected',
  'Fon başvuru dosyası': 'Fund application',
  'Tinos (Times uyumlu)': 'Tinos (Times compatible)',
  'Geri dönmek yazdıklarını silmez — dönmeden önce şu anki hâlin de kaydedilir, istersen buraya geri gelebilirsin.': 'Going back never deletes your writing — the current state is saved first, so you can return here anytime.',
  'Geri dönüş noktaları': 'Restore points',
  'Geçiş': 'Transition',
  'Geçiş süresi': 'Transition duration',
  'Gizle': 'Hide',
  'Görünecek ad': 'Display name',
  'Görünür': 'Visible',
  'Göster': 'Show',
  'Günlüğün sonu eksik': 'The end of the journal is missing',
  'Hareket okunu göster': 'Show motion arrow',
  'Henüz kayıt yok.': 'No entries yet.',
  'Henüz kimse katılmadı.': 'No one has joined yet.',
  'Henüz sürüm yok.': 'No versions yet.',
  'Hiçbir şey kaybolmaz.': 'Nothing is ever lost.',
  'Kadro': 'Cast',
  'Kamera': 'Camera',
  'Kamera Açısı': 'Camera Angle',
  'Kareler hazırlanıyor…': 'Preparing frames…',
  'Karışım': 'Blend',
  'Karşılaştırılıyor…': 'Comparing…',
  'Katman': 'Layer',
  'Katman ekle': 'Add layer',
  'Katmanlar': 'Layers',
  'Arka Plan': 'Background',
  'Kaydedildi': 'Saved',
  'Kaydedilemedi': 'Save failed',
  'Kaydedilmemiş': 'Unsaved work of',
  'Kaydedilmemiş değişiklikler var. Devam edilsin mi?': 'There are unsaved changes. Continue?',
  'Kaydır (basılı tutarken)': 'Pan (while held)',
  'Kelime': 'Words',
  'Kelime ekle': 'Add word',
  'Kemik': 'Bone',
  'Kemik seçim modu': 'Bone selection mode',
  'Kilidi aç': 'Unlock',
  'Kilitle': 'Lock',
  'Kilitli': 'Locked',
  'Kilitli haritayı değiştirmek istiyor musunuz?': 'Change the locked map?',
  'Yeni coğrafya yalnızca önizleme olarak açılır. Beğenmezseniz mevcut harita korunur.': 'The new geography opens as a preview only. Your current map is kept if you cancel.',
  'Yeniden oluştur': 'Regenerate',
  'Haritayı koru': 'Keep map',
  'Haritayı kilitle': 'Lock map',
  'Harita kilidini aç': 'Unlock map',
  'Önizleme': 'Preview',
  'İşaretler yeni haritada denize düşebilir; konumları ve bağlantıları korunur.': 'Markers may land in the sea on the new map; their positions and links are preserved.',
  'Kim Ne Yazdı': 'Who Wrote What',
  'Kitaplık': 'Library',
  'Klavye Kısayolları': 'Keyboard Shortcuts',
  'Kopyala': 'Copy',
  'Kes': 'Cut',
  'Yapıştır': 'Paste',
  'Tümünü seç': 'Select all',
  'Panel oluştur ve bağla': 'Create and link panel',
  'Aktif panele bağla': 'Link to active panel',
  'Yer imi koy': 'Add bookmark',
  'Bağlı panele git': 'Go to linked panel',
  'Bu kelimeyi yoksay': 'Ignore this word',
  'Kopyalanamadı.': 'Could not copy.',
  'SENARYONUN ADI': 'SCREENPLAY TITLE',
  'alt başlık (isteğe bağlı)': 'subtitle (optional)',
  'Yazar adı — birden fazlaysa alt alta': 'Author name — one per line if more than one',
  'Ajans / telefon / e-posta': 'Agency / phone / email',
  '1. taslak': '1st draft',
  'tarih': 'date',
  'Kapak sayfası': 'Cover page',
  'Kapak sayfasını göster': 'Show cover page',
  'Akıllı yazım düzeltmeleri': 'Smart text corrections',
  'Yazarken düzeltir: MErhaba→Merhaba, üç nokta→…, iki tire→—, kıvırcık tırnak, çift boşluk. Hepsi Ctrl+Z ile geri alınır.':
    'Fixes as you type: MErhaba→Merhaba, three dots→…, double hyphen→—, curly quotes, double spaces. All undoable with Ctrl+Z.',
  'Daktilo modu': 'Typewriter mode',
  'İmleç ekranın ortasında kalır, yazdığın satır vurgulanır, ötekiler hafifçe söner.':
    'The cursor stays centred, the line you are writing is highlighted, the rest dims slightly.',
  'Arayüz ölçeği': 'Interface scale',
  'Senaryo sayfası bundan etkilenmez — sayfa sayısı değişmez.':
    'The screenplay page is unaffected — the page count does not change.',
  'Numaralandırma': 'Numbering',
  'Sahne no': 'Scene no.',
  'Diyalog no': 'Dialogue no.',
  'Kapalı': 'Off',
  'Solda': 'Left',
  'Sağda': 'Right',
  'İki yanda': 'Both sides',
  'Kenar boşluğunda görünür — sayfa sayısını değiştirmez.':
    'Shown in the margin — does not change the page count.',
  'Sayfa sonu sürekliliği': 'Page-break continuity',
  'Bölünen diyaloğa (DEVAMI VAR) / (DEVAM) ekle': "Add (MORE) / (CONT'D) to split dialogue",
  'DİKKAT: satır eklediği için SAYFA SAYISINI değiştirir.':
    'NOTE: adds lines, so it CHANGES the page count.',
  'Süre hesabı': 'Duration',
  'Yöntem': 'Method',
  'Sayfa sayısından': 'From page count',
  'Harf sayısından': 'From character count',
  'Blok başına özel': 'Custom per block',
  '1 sayfa ≈ 1 dakika — sektör sözleşmesi.': '1 page ≈ 1 minute — the industry convention.',
  'Sayfa sayısıyla ilgisi yok — bu modda "1 sayfa ≈ 1 dakika" geçerli değil.':
    'Unrelated to page count — the "1 page ≈ 1 minute" convention does not apply in this mode.',
  'dk': 'min',
  'Sayfa sayısından hesaplandı': 'Computed from page count',
  'Harf sayısından hesaplandı — sayfa sayısıyla ilgisi yok':
    'Computed from character count — unrelated to page count',
  'Blok başına özel kurallarla hesaplandı — sayfa sayısıyla ilgisi yok':
    'Computed with custom per-block rules — unrelated to page count',
  'Görünüm': 'Appearance',
  'Yazma': 'Writing',
  'Senaryo biçimi': 'Screenplay format',
  'Değiştirilemeyen ölçüler': 'Fixed measures',
  'Başlangıç': 'Startup',
  'Yazım presetleri': 'Line presets',
  'Belge dili': 'Document language',
  'Belge dili sahne başlığı terimlerini belirler (İÇ./INT.) — arayüz dilinden ayrıdır.':
    'The document language sets scene-heading terms (INT./EXT.) — separate from the interface language.',
  'Daktilo sesi': 'Typewriter sound',
  'Tuşlara basarken mekanik daktilo sesi çıkar.': 'Plays a mechanical typewriter sound on keypress.',
  'Senaryonun ilk sayfası olarak düzenlenebilir kapak. Sayfa sayısına girmez.':
    'An editable cover as the first page of the screenplay. Not counted in the page count.',
  'PC açılınca otomatik başlat': 'Start automatically on boot',
  'Bilgisayar açıldığında Auteur otomatik olarak başlar.': 'Auteur starts automatically when the computer boots.',
  'Küçültülmüş başla': 'Start minimised',
  'Otomatik başladığında pencere görev çubuğunda küçültülmüş açılır.':
    'When auto-started, the window opens minimised to the taskbar.',
  'Ayarlar okunamadı': 'Could not read settings',
  'Ayar kaydedilemedi': 'Could not save setting',
  'Punto': 'Font size',
  'Satır aralığı': 'Line spacing',
  'Senaryo sayfasında çıplak harf kısayolu yoktur': 'Bare letter shortcuts do not work on the screenplay page',
  'yazarken kaza olmasın diye': 'to prevent accidents while typing,',
  'gerekir. Panoda harfler doğrudan çalışır.': 'is required. On the board, letters work directly.',
  'Dosya türü': 'File type',
  '.sbp dosyalarına Auteur simgesi verir ve çift tıklayınca bu programla açılmalarını sağlar. Yalnız bu kullanıcı için, yönetici yetkisi gerekmez.':
    'Gives .sbp files the Auteur icon and makes double-click open them in this program. For this user only; no administrator rights needed.',
  '.sbp dosyalarını Auteur ile aç': 'Open .sbp files with Auteur',
  '.sbp dosyaları artık Auteur ile açılıyor.': '.sbp files now open with Auteur.',
  'Yapılamadı': 'Could not do it',
  'Dosyadan aç…': 'Open from file…',
  'Belgenin türü': 'Document type',
  'Mühür alınamadı': 'The seal could not be recorded',
  'Belgenin dili kurumun şartı; bu belgede değiştirilemez.': "The document's language is set by the institution and cannot be changed here.",
  /* ---- Mühür ve kanıt ---- */
  'Mühür': 'Seal',
  'Mühür ve kanıt…': 'Seal and proof…',
  'Mühürle': 'Seal now',
  'Mühür alındı.': 'Seal recorded.',
  'elle mühürlendi': 'sealed by hand',
  'Zaman damgası alındı.': 'Timestamp obtained.',
  'Zaman damgası alınamadı': 'The timestamp could not be obtained',
  'Zaman damgası sunucusu': 'Timestamp authority',
  'Kanıt paketi kaydet': 'Save the proof package',
  'Kanıt paketi': 'Proof package',
  'Kanıt paketi üretilemedi': 'The proof package could not be built',
  'Zincir': 'Chain',
  'kayıt': 'records',
  'sağlam': 'intact',
  'bağ kopuk': 'link broken',
  'dosya bozuk': 'file corrupt',
  'damgalı': 'timestamped',
  'damga al': 'get a timestamp',
  'Henüz mühür yok. "Mühürle" bu andaki metni zincire işler.': 'No seals yet. "Seal now" records the text as it stands into the chain.',
  'Mühür zinciri bu kabukta yok: tarayıcıda kalıcı bir kanıt dosyası tutulamıyor ve zaman damgası sunucularına doğrudan bağlanılamıyor. Masaüstü sürümünde kullanılabilir.': 'The seal chain is not available in this shell: a browser cannot keep a persistent proof file and cannot reach timestamp authorities directly. It works in the desktop build.',
  'Yerel zincir bu metnin bu sırayla var olduğunu kanıtlar; tarihi kanıtlamaz — saat bu makinenindir.': 'The local chain proves this text existed in this order; it does not prove the date — the clock belongs to this machine.',
  'Zaman damgası, bağımsız bir otoritenin bu özetin belirtilen tarihten önce var olduğunu imzalamasıdır.': 'A timestamp is an independent authority signing that this digest existed before the stated date.',
  'Yalnız "damga al" dediğinde bu adrese bağlanılır ve gönderilen şey metnin özetidir, metnin kendisi değil.': 'This address is contacted only when you ask for a timestamp, and what is sent is the digest of the text, never the text itself.',
  /* ---- Fon başvuru dosyası ---- */
  'Fon dosyası kontrol listesi…': 'Funding application checklist…',
  'Belgedeki bölümler': 'Sections in the document',
  'Paket oluştur': 'Build the package',
  'Paket üretilemedi': 'The package could not be built',
  'Başvuru paketi': 'Application package',
  'bulunamadı': 'not found',
  'sınır aşıldı': 'over the limit',
  'dolu': 'filled',
  'boş': 'empty',
  'Bu belgede fon şablonu kayıtlı değil; kontrol listesi kurulamıyor. Belgeyi senaryodan yeniden oluşturman gerekiyor.': 'No funding template is recorded in this document, so the checklist cannot be built. Recreate the document from the screenplay.',
  'kaynak': 'source',
  'Başvuru kanalı': 'Application channel',
  'Kurumun ek listesi yıllık değişiyor. Başvurudan önce güncel listeyi kurumdan doğrula.': "The institution's list of attachments changes each year. Verify the current list with the institution before you apply.",
  'Teslim kuralları': 'Submission rules',
  'Kabul edilen biçimler': 'Accepted formats',
  'Dosya başına azami boyut': 'Maximum size per file',
  'Filmin özgün adı her belgenin içinde geçmeli.': 'The original title of the film must appear inside every document.',
  'Dosya adları içeriğine atıfta bulunmalı.': 'File names must refer to their content.',
  'Eksik ek başvuruyu doğrudan eler.': 'A missing attachment makes the application ineligible.',
  'Pakete giren dosyalar': 'Files in this package',
  'EKSİK — zorunlu ama boş': 'MISSING — required but empty',
  'gövdesi boş': 'body is empty',
  'belgede bulunamadı (başlığı değiştirilmiş olabilir)': 'not found in the document (its heading may have been changed)',
  'SINIR AŞIMI': 'OVER THE LIMIT',
  'Sayfa ölçümü PDF üzerinden yapılmıştır; DOCX sayfalamayı Word yapar.': 'Page counts are measured on the PDF; Word paginates the DOCX itself.',
  'BOYUT AŞIMI': 'OVER THE SIZE LIMIT',
  'Dışarıdan alınacak ekler (Auteur üretmez)': 'Attachments obtained elsewhere (Auteur does not produce these)',
  'varsa': 'if any',
  'Bu senaryodan fon dosyası oluştur': 'Create a funding application from this screenplay',
  'Bu senaryodan fon dosyası oluştur…': 'Create a funding application from this screenplay…',
  'Fon dosyası': 'Funding application',
  'Kurum ve destek türü': 'Institution and support scheme',
  'sürüm': 'version',
  'Kurumun ek listesi': "The institution's list of attachments",
  'Belgede bölüm olarak kurulacak': 'Set up as sections in the document',
  'senaryodan taslağı çıkarılacak': 'drafted from the screenplay',
  'dışarıdan alınacak (noter, oda kaydı vb.)': 'obtained elsewhere (notary, chamber of commerce, etc.)',
  'Fon dosyası ayrı bir belgedir ve şu anki senaryodan kopyalanır. Senaryo sonradan değişirse fon dosyası kendiliğinden güncellenmez; fon belgesindeki "Senaryodan tazele" düğmesi türetilen bölümleri yeniler, elle yazdıklarına dokunmaz. Kurumun güncel ek listesini başvurudan önce doğrula.': 'The funding application is a separate document, copied from the screenplay as it stands now. It does not update itself when the screenplay changes; the "Refresh from screenplay" button in the funding document renews the derived sections and leaves what you wrote by hand untouched. Verify the current list of attachments with the institution before you apply.',
  'Senaryodan tazele': 'Refresh from screenplay',
  'Kaynak senaryo': 'Source screenplay',
  'tarihinde türetildi': 'is when it was derived',
  '"Senaryodan tazele" yalnız türetilen bölümleri yeniler; elle yazdıkların olduğu gibi kalır.': '"Refresh from screenplay" renews only the derived sections; whatever you wrote by hand stays as it is.',
  'Tazeleme iptal edildi.': 'Refresh cancelled.',
  'Seçilen dosya bu fon belgesinin kaynağı değil. Yine de bundan tazelensin mi?': 'The file you picked is not the source of this funding document. Refresh from it anyway?',
  'Belge açık değil.': 'No document is open.',
  'Yenilenecek türetilmiş bölüm bulunamadı.': 'No derived section was found to renew.',
  'Tazelendi': 'Refreshed',
  'Belgede bulunamadığı için atlandı': 'Skipped, not found in the document',
  'Tazelenemedi': 'Could not refresh',
  'sayfa süreyi ölçmez': 'pages do not measure time',
  /* Doküman tipi açıklamaları — tanım yeri `model/dokuman-tipi.ts`. */
  'Amerikan tek sütun: sahne başlığı, tam genişlik aksiyon, ortada dar diyalog sütunu.': 'American single column: scene heading, full-width action, a narrow dialogue column in the centre.',
  'Senaryonun aynısı; üstünde bölüm katmanı var, gezgin ve analiz bölümle sayar.': 'The same as a screenplay, with an episode layer above it; the navigator and the analysis count by episode.',
  'Perde ve sahne. Aksiyonun yerinde sahne yönergesi — oyuncuya verilen yönerge, kameranın gördüğü değil.': 'Acts and scenes. Stage directions stand where action would: what the actor is told, not what the camera sees.',
  'Ses ve müzik ayrı bloklar; aranabilir ve sayılabilir. Anlatının yarısı onlarda kurulur.': 'Sound and music are separate blocks, searchable and countable. Half the storytelling is built in them.',
  'Bölüm ve paragraf; ilk satır girintili. Sayfa burada süre ölçmez.': 'Chapters and paragraphs, first line indented. A page does not measure time here.',
  'Sayfa, kare, balon. Yapı birimi sahne değil sayfadır.': 'Page, panel, balloon. The structural unit is the page, not the scene.',
  'Tek blok: paragraf. Biçim dayatmayan boş sayfa — not, tretman, sinopsis.': 'One block: the paragraph. A blank page that imposes no format — notes, treatment, synopsis.',
  'İki sütun: solda görüntü, sağda ses. Ayrı sayfalayıcı; birim satır değil satır çifti.': 'Two columns: image on the left, sound on the right. A separate paginator; the unit is the line pair, not the line.',
  'Bu filtreye uyan satır yok.': 'No lines match this filter.',
  'Bu filtreye uyan panel yok.': 'No cards match these filters.',
  'Dünyalar': 'Worlds',
  'Harita': 'Map',
  'Uygula': 'Apply',
  'Haritayı aç': 'Open map',
  'Dünya haritası': 'World map',
  'Harita ayarları': 'Map settings',
  'Ülke': 'Country',
  'Ülkeler': 'Countries',
  'Ülke sayısı': 'Country count',
  'Ülke özellikleri': 'Country properties',
  'Arazi': 'Terrain',
  'Düzlük': 'Plain',
  'Orman': 'Forest',
  'Çöl': 'Desert',
  'Bataklık': 'Swamp',
  'Tundra': 'Tundra',
  'Volkanik': 'Volcanic',
  'Harita rengi': 'Map color',
  'Harita görünümü': 'Map appearance',
  'Harita yükleniyor…': 'Loading map…',
  'Doku': 'Texture',
  'Özel dokular': 'Custom textures',
  'Deniz ve göller': 'Sea and lakes',
  'Varsayılan': 'Default',
  'Bozuk kayıt': 'Broken record',
  'Doku doğrulanıyor…': 'Verifying texture…',
  'Sahipsiz arazi': 'Unclaimed land',
  'Proje dünya haritası': 'Project world map',
  'Bu projede henüz bir dünya haritası yok.': 'This project has no world map yet.',
  'Rastgele dünya oluştur': 'Create random world',
  'Eski haritayı içe al': 'Import an older map',
  'Kaynak haritalar ve görselleri korunur; yalnızca seçtiğiniz kopyalanır.': 'Source maps and their images remain untouched; only your selection is copied.',
  'Önce bir dünya haritası oluşturun veya eski bir haritayı içe alın.': 'Create a world map or import an older map first.',
  'Doğal arazi': 'Natural terrain',
  'Nem': 'Moisture',
  'Harita katmanları': 'Map layers',
  'Yeryüzü': 'Terrain',
  'Nehirler': 'Rivers',
  'Etiketler': 'Labels',
  'Doku yüklenemedi; sıfırlayıp yeniden ekleyin.': 'Texture could not be loaded. Reset it and add it again.',
  'Doku yüklenemedi': 'Texture could not be loaded',
  'Deniz dokusu yüklenemedi': 'Sea texture could not be loaded',
  'Doku en fazla 4 MB ve 2048 piksel olabilir.': 'Texture must be at most 4 MB and 2048 pixels per side.',
  'Doku dosyası okunamadı.': 'Could not read the texture file.',
  'PNG/JPG seç': 'Choose PNG/JPG',
  'Sıfırla': 'Reset',
  'Özel deniz dokusuyla PNG olarak dışa aktar': 'Export PNG with custom sea texture',
  'Özel renk, Renk görünümünde gösterilir.': 'Custom color appears in Color view.',
  'Not': 'Note',
  'Arazi rengine dön': 'Use terrain color',
  'Sınırlar değişebilir; ülke adları ve notları korunur.': 'Borders may change; country names and notes are preserved.',
  'Mekânlar': 'Places',
  'Görseller': 'Images',
  'Coğrafya': 'Geography',
  'Tohum': 'Seed',
  'Kara miktarı': 'Land amount',
  'Ada sayısı': 'Island count',
  'Göl sayısı': 'Lake count',
  'Ülke merkezleri arası en az': 'Minimum distance between country centers',
  'Göller bu kara alanına sığmıyor. Göl sayısını azaltın veya kara miktarını değiştirin.': 'The lakes do not fit on this land. Reduce the lake count or change the land amount.',
  'Ülkeler bu aralıkla sığmıyor. Aralığı veya ülke sayısını azaltın; coğrafyayı ya da tohumu değiştirin.': 'The countries do not fit at this spacing. Reduce the spacing or country count, or change the geography or seed.',
  'Yeni kıyı taslağı': 'Preview new coast',
  'Geçersiz harita ayarı': 'Invalid map setting',
  'Tohum ve ayarlar kaydedilir; aynı değerler aynı kıyıyı üretir.': 'Seed and settings are saved; the same values produce the same coast.',
  'Taslak': 'Draft',
  'Mekân işaretleri': 'Place markers',
  'Bağlı mekân': 'Linked place',
  'Bağsız işaret': 'Unlinked marker',
  'Bağlı mekân bulunamadı': 'Location not found',
  'Yeni mekân': 'New place',
  'Yeni etiket': 'New label',
  'Haritada bir noktaya tıkla': 'Click a point on the map',
  'İşaret yerleştir': 'Place marker',
  'Yazı yerleştir': 'Place label',
  'Henüz işaret yok.': 'No markers yet.',
  'İşaret özellikleri': 'Marker properties',
  'İşaret adı': 'Marker name',
  'Mekân notunu aç': 'Open place note',
  'Mekân açıklaması': 'Place description',
  'Mekân notları': 'Place notes',
  'İşareti sil': 'Delete marker',
  'Yazı özellikleri': 'Label properties',
  'Harita yazısı': 'Map label',
  'Yazıyı sil': 'Delete label',
  'Görsel katmanları': 'Image layers',
  'PNG/JPG görselleri haritanın üstüne yerleştir.': 'Place PNG/JPG images over the map.',
  'Görsel özellikleri': 'Image properties',
  'Görseli kaldır': 'Remove image',
  'Gizli': 'Hidden',
  'Döndür': 'Rotate',
  'Yalnızca PNG/JPG görseller eklenebilir.': 'Only PNG/JPG images can be added.',
  'Görsel boyutu sınırı aşıyor.': 'Image exceeds the size limit.',
  'Görsel dosyası okunamadı.': 'Could not read the image file.',
  'Görsel yüklemesi iptal edildi.': 'Image upload was cancelled.',
  'Görsel yerleşimi geçersiz.': 'Invalid image placement.',
  'Görsel okunuyor…': 'Reading image…',
  'PNG/JPG ekle': 'Add PNG/JPG',
  'Harita dışa aktarılamadı.': 'Could not export the map.',
  'Haritayı saydam PNG olarak dışa aktar': 'Export map as transparent PNG',
  'Haritayı JPG olarak dışa aktar': 'Export map as JPG',
  'Geri Dönüşüm Kutusu': 'Recycle Bin',
  'Henüz hiç dünya notu yok.': 'No world notes yet.',
  'Konuşan karakter yok.': 'No speaking characters.',
  'Kutu boş.': 'The bin is empty.',
  'Proje adı': 'Project name',
  'Proje sözlüğü': 'Project dictionary',
  'Sayfa başına': 'Per page',
  'Senaryoda hiç karakter yok.': 'No characters in the screenplay.',
  'Senaryoda hiç sahne başlığı yok.': 'No scene headings in the screenplay.',
  'Senaryonu buraya sürükle': 'Drag your screenplay here',
  'Sonuç bulunamadı.': 'No results.',
  'Sözlükte kelime yok.': 'No words in the dictionary.',
  'Tüm sahneler': 'All scenes',
  'bugünden itibaren': 'from today onward',
  'hepsi ya da hiçbiri': 'all or nothing',
  'panel düzenliyor': 'editing a panel',
  'tek kişilik': 'solo',
  'Çoğalt': 'Duplicate',
  'İptal': 'Cancel',
  'Geri': 'Back',
  'Auteur iki şeyi bir arada yapar: senaryo yazmak ve o senaryoyu görsel olarak planlamak (storyboard).': 'Auteur does two things at once: writing a screenplay and planning it visually (storyboard).',
  'Auteur nasıl çalışır?': 'How does Auteur work?',
  'Ayarlar → Dosya türü bölümündeki düğmeye bas: .sbp dosyaları Auteur ile ilişkilendirilir.': 'Press the button in Settings → File type: .sbp files get associated with Auteur.',
  'Aynı senaryoyu başkasıyla yazabilir miyim?': 'Can I write the same screenplay with someone else?',
  'Bağlantıyı paylaş. Karşı taraf tarayıcıdan da katılabilir, program kurması gerekmez.': 'Share the link. The other person can join from a browser — no installation needed.',
  'Başlarken': 'Getting started',
  'Belgenin türünü seç (senaryo, roman, oyun…). Bu seçim sayfa düzenini belirler ve sonradan değişmez.': 'Choose the document type (screenplay, novel, play…). This sets the page layout and cannot be changed later.',
  'Bir şeyler ters gidiyor': 'Something is going wrong',
  'Birlikte çalışma': 'Working together',
  'Bu arada dosyalar Auteur simgesini de alır.': 'They also pick up the Auteur icon at the same time.',
  'Bu ayarları aç': 'Open these settings',
  'Bu dosyayı istediğin klasöre koyabilir, e-postayla gönderebilir, yedekleyebilirsin. Tek dosya taşındığında her şey taşınır.': 'You can put that file in any folder, email it, or back it up. Move the one file and everything moves with it.',
  'Bu normaldir ve bir kereliktir: Windows Defender programı ilk kez baştan sona tarar. Sonraki açılışlar bir saniye sürer.': 'That is normal and happens once: Windows Defender scans the program end to end the first time. Later launches take about a second.',
  'Bu uyarıyı gördüğünde önemli bir metni uzun süre yazmaya devam etme; önce projeyi kaydet.': 'When you see this warning, do not keep writing important material for long — save the project first.',
  'Bunun dışında program kendi güvenlik kopyalarını da tutar — kurtarma kayıtları ve sürüm geçmişi. Onlar bilgisayarındaki uygulama klasöründedir ve programı kaldırsan bile silinmez.': 'Separately, the program keeps its own safety copies — recovery records and version history. They live in the application folder on your computer and are not deleted even if you uninstall.',
  'Büyük ihtimalle hayır. Auteur yazdığın her şeyi saniyede bir diske kaydeder — kaydet düğmesine basmasan bile.': 'Almost certainly not. Auteur writes everything you type to disk every second — even if you never press Save.',
  'Dosyalarım nerede?': 'Where are my files?',
  'Dışa aktar düğmesinden PDF alırsın — sektörde teslim biçimi budur.': 'Use Export to produce a PDF — that is how screenplays are delivered.',
  'Dışa aktarma': 'Exporting',
  'Dışa aktarma penceresini aç': 'Open the export window',
  'Ekrandaki sayfa rengi çıktıya YANSIMAZ. Koyu bir sayfada yazsan bile PDF her zaman beyaz zemine siyah yazı olarak çıkar.': 'The page colour on screen does NOT reach the export. Even if you write on a dark page, the PDF is always black text on white.',
  'Ekranın altında "çökme koruması yok" yazıyor.': 'It says "no crash protection" at the bottom of the screen.',
  'En sık karşılaşılan üç durum ve çözümleri aşağıda.': 'The three most common situations and their fixes are below.',
  'Evet. Bir oturum açıp davet bağlantısı paylaşırsın; ikiniz aynı anda yazabilirsiniz.': 'Yes. Start a session and share the invite link; you can both write at the same time.',
  'Final Draft (.fdx) ve Fountain — başka senaryo programlarına aktarmak için.': 'Final Draft (.fdx) and Fountain — to move into other screenwriting programs.',
  'Geri alma (Ctrl+Z) — az önce yaptığın değişiklik için.': 'Undo (Ctrl+Z) — for the change you just made.',
  'Geri dönmek yazdıklarını SİLMEZ: dönmeden önce şu anki hâlin de kaydedilir, istersen geri gelebilirsin.': 'Going back never DELETES anything: the current state is saved first, so you can always return.',
  'Geri dönüş noktaları — program her beş dakikada bir durumu kaydeder; bugünün herhangi bir anına dönebilirsin.': 'Restore points — the program saves the state every five minutes; you can go back to any moment today.',
  'Geri dönüş noktalarını aç': 'Open restore points',
  'Herkesin imleci kendi renginde görünür. Kimin ne yazdığı ayrıca kaydedilir — bir replik için "bunu kim yazdı" sorusunu sorabilirsin.': 'Everyone\'s cursor appears in their own colour. Who wrote what is recorded separately — you can ask "who wrote this line".',
  'Kaydettiğin yerde. Auteur projeni .sbp uzantılı tek bir dosyaya yazar; içinde senaryo, storyboard ve görseller birlikte durur.': 'Wherever you saved them. Auteur writes your project into a single .sbp file that holds the screenplay, the storyboard and the images together.',
  'Kağıt boyutu — A4 ve US Letter farklı yükseklikte.': 'Paper size — A4 and US Letter are different heights.',
  'Kim ne yazdı penceresini aç': 'Open the "who wrote what" window',
  'Kitaplık ekranında "Yeni proje" ile başla.': 'Start with "New project" on the Library screen.',
  'Kitaplıkta bir proje görünüyor ama açılmıyorsa, dosya taşınmış ya da silinmiş demektir.': 'If a project shows in the Library but will not open, the file has been moved or deleted.',
  'Klavye kısayollarını gör': 'See keyboard shortcuts',
  'Masaüstü programında bu yazı çıkıyorsa diske yazma engellenmiş demektir — diskin dolu olup olmadığına bak.': 'If you see this in the desktop program, writing to disk is blocked — check whether the disk is full.',
  'Menü → Ortak çalışma oturumu.': 'Menu → Collaboration session.',
  'Metni değiştirmediysen, sayfa sayısını etkileyen bir ayarı açmışsındır.': 'If you did not change the text, you turned on a setting that affects the page count.',
  'Oturum penceresini aç': 'Open the session window',
  'Oturumu başlat; sana bir oda kodu ve davet bağlantısı verilir.': 'Start the session; you get a room code and an invite link.',
  'PDF — teslim için. Sayfa düzeni editörde gördüğünle aynıdır.': 'PDF — for delivery. The page layout matches what you see in the editor.',
  'Program ilk açılışta çok yavaş açıldı.': 'The program was very slow the first time it opened.',
  'Program çökse, elektrik kesilse ya da bilgisayar kapansa bile en fazla son bir saniyen kaybolur. Programı tekrar açtığında kurtarma penceresi çıkar ve ne bulduğunu sorar.': 'If the program crashes, the power goes out or the computer shuts down, you lose at most the last second. When you reopen it, a recovery window tells you what it found and asks what to do.',
  'Proje dosyasına çift tıklıyorum, açılmıyor.': 'I double-click a project file and nothing opens.',
  'Projelerim nerede saklanıyor?': 'Where are my projects stored?',
  'Roller: sahip her şeyi yapar, editör yazar, yorumcu yalnız okur ve işaretleme katmanına çizer.': 'Roles: the owner can do everything, an editor writes, a commenter only reads and draws on the markup layer.',
  'Sayfa düzeni sektör standardıdır: yazı tipi, punto ve satır aralığı değiştirilemez. Bunun sebebi "1 sayfa ≈ 1 dakika" sözleşmesidir — ölçüler değişirse süre tahmini yalan söyler.': 'The page layout is the industry standard: typeface, size and line spacing cannot be changed. This is what makes "1 page ≈ 1 minute" hold — change the measures and the running time starts lying.',
  'Sayfa sayım neden değişti?': 'Why did my page count change?',
  'Sayfa sayısı değişti': 'The page count changed',
  'Sayfa sayısını DEĞİŞTİRMEYEN ayarlar: sayfa rengi, arayüz ölçeği, sahne numarası gösterimi, daktilo modu. Bunlar yalnız ekranı etkiler.': 'Settings that do NOT change the page count: page colour, interface scale, scene numbering, typewriter mode. Those affect the screen only.',
  'Sayfa sayısını değiştiren ayarlar:': 'Settings that change the page count:',
  'Sayfa sonu sürekliliği — bölünen diyaloğa (DEVAMI VAR)/(DEVAM) satırları ekler; her bölünme iki satır demektir.': 'Page-break continuity — adds (MORE)/(CONT\'D) lines to split dialogue; each split costs two lines.',
  'Senaryomu nasıl teslim ederim?': 'How do I deliver my screenplay?',
  'Senaryonu yazarsın, programda sayfa sayısı ve süre kendiliğinden hesaplanır.': 'You write your screenplay; the page count and running time are worked out for you.',
  'Silinen projeler kitaplıktan kendiliğinden kalkar.': 'Deleted projects disappear from the Library on their own.',
  'Sorun giderme': 'Troubleshooting',
  'Storyboard PDF, PNG dizisi ve animatik video — görsel plan için.': 'Storyboard PDF, PNG sequence and animatic video — for the visual plan.',
  'Süre hesabını "harf sayısından" ya da "blok başına özel" yaparsan, gösterilen süre artık sayfa sayısına bağlı değildir — "1 sayfa ≈ 1 dakika" sözleşmesi o modlarda geçerli olmaz.': 'If you set the duration to "from character count" or "custom per block", the time shown no longer follows the page count — the "1 page ≈ 1 minute" convention does not apply in those modes.',
  'Sürüm geçmişi — her kaydettiğinde bir sürüm saklanır; günler öncesine dönebilirsin.': 'Version history — a version is kept every time you save; you can go back days.',
  'Sürüm geçmişini aç': 'Open version history',
  'Tarayıcıdan bağlandığın oturumlarda bu koruma yoktur; yazdıkların yalnız sunucuya gider.': 'Sessions joined from a browser do not have this protection; your writing goes to the server only.',
  'Teslim etmeden önce başlık sayfasını doldur: senaryonun ilk sayfası olarak düzenlenir, adın ve iletişim bilgin oraya yazılır.': 'Fill in the title page before delivering: it is edited as the first page of the screenplay and carries your name and contact details.',
  'Word (.docx) — ölçüler korunur ama sayfalamayı Word kendi yapar.': 'Word (.docx) — the measures are kept, but Word does its own pagination.',
  'Yardım': 'Help',
  'Yardım Merkezi': 'Help Centre',
  'Yazdıklarım kayboldu mu?': 'Have I lost my writing?',
  'Yazdığın bir şeyi geri getirmek istiyorsan üç yolun var:': 'There are three ways to bring back something you wrote:',
  'Yazmaya başla. Satırın türünü (sahne başlığı, diyalog…) Ctrl+1…9 ile değiştirirsin.': 'Start writing. Change the line type (scene heading, dialogue…) with Ctrl+1…9.',
  'çıktıda varsayılan olarak yok': 'absent from the output by default',
  'Önce bir revizyon açın.': 'Open a revision first.',
  'Önce işaretlenecek satırları seçin.': 'Select the lines to mark first.',
  'Üstteki sekmelerden Kartlar ve Storyboard görünümlerine geçebilirsin.': 'Use the tabs at the top to switch to the Cards and Storyboard views.',
  'sahne': 'scene',
  'kaydedildi': 'saved',
  'Esc — çık': 'Esc — exit',
  'Panel kimliği': 'Panel ID',
  '(başlıksız)': '(untitled)',
  '(boş satır)': '(empty line)',
  '+ Karakter bağla…': '+ Link character…',
  '+ Lokasyon bağla…': '+ Link location…',
  '1 gün': '1 day',
  '10 kişi': '10 people',
  '3 kişi': '3 people',
  '50 kişi': '50 people',
  'API anahtarı': 'API key',
  'Alt başlık': 'Subtitle',
  'Açık': 'On',
  'Aşağı': 'Down',
  'Başlık': 'Title',
  'Bu adres YALNIZ bu bilgisayarda çalışır. Davetli başka bir': 'This address works ONLY on this computer. If your guest is on another',
  'Bu ana dön': 'Go back to this moment',
  'Bu bölüm yalnızca masaüstü uygulamasında kullanılabilir.': 'This section is available in the desktop app only.',
  'Bu satır imli': 'This line is bookmarked',
  'Bu satırı kim yazdı': 'Who wrote this line',
  'Bu sürümde anahtar saklanmıyor — yalnız bu oturumda geçerli.': 'The key is not stored in this version — it applies to this session only.',
  'Bu sürümle aradaki senaryo farkı yok.': 'No screenplay difference from this version.',
  'Davet linki üret': 'Generate invite link',
  'Davetliler bu sunucu üzerinden internet üzerinden bağlanır; kurulum gerekmez.': 'Guests connect over the internet through this server; no installation needed.',
  'Değiştir': 'Change',
  'Esc · Çık': 'Esc · Exit',
  'Farklı kaydet': 'Save as',
  'Fransız (iki sütun) — sayfa süreyi ölçmez': 'French (two column) — pages do not measure time',
  'Geri yükle': 'Restore',
  'Geçen hafta kim ne yaptı': 'Who did what last week',
  'Görsel ekle (ya da canvas\'a sürükleyin)': 'Add an image (or drag onto the canvas)',
  'Gösterilecek panel yok.': 'No panel to show.',
  'Henüz geri dönülecek bir an yok — program yazdıkça birikir.': 'No moment to return to yet — they accumulate as you write.',
  'Henüz kayıt yok; program yazdıkça birikir.': 'No records yet; they accumulate as you write.',
  'Henüz yer imi yok.': 'No bookmarks yet.',
  'Hız': 'Pace',
  'Kalıcı sil': 'Delete permanently',
  'Kalınlık': 'Thickness',
  'Kamera Açıları': 'Camera Angles',
  'Kamerayı sıfırla': 'Reset camera',
  'Karşılaştırılacak sürüm yok.': 'No version to compare.',
  'Kelime boş olamaz, harf içermeli ve 64 karakteri aşmamalı.': 'The word cannot be empty, must contain letters and must not exceed 64 characters.',
  'Kostüm': 'Costume',
  'Kütüphane': 'Library',
  'Oluştur': 'Create',
  'Oturum başlat': 'Start session',
  'PNG dizisi oluştur': 'Create PNG sequence',
  'Panele sabitle (performans için PNG\'ye çevir)': 'Flatten into the panel (convert to PNG for performance)',
  'Proje 60 saniyede bir otomatik kaydedilir; ilk sürüm oluştuğunda burada listelenir.': 'The project is saved automatically every 60 seconds; the first version will be listed here.',
  'Proje 60 saniyede bir otomatik kaydedilir; son 10 sürüm yerelde saklanır.': 'The project is saved automatically every 60 seconds; the last 10 versions are kept locally.',
  'Proje aç (.sbp)': 'Open project (.sbp)',
  'Rol denetimi sunucu tarafında zorunlu kılınır; arayüzü değiştirmek yetki kazandırmaz.': 'Roles are enforced on the server; changing the interface grants no permissions.',
  'Salt okunur — bu rolde ana katman düzenlenemez': 'Read only — this role cannot edit the main layer',
  'Sağlayıcı': 'Provider',
  'Serbest ayarı bitir': 'Finish free adjustment',
  'Seç': 'Select',
  'Süre (dk)': 'Duration (min)',
  'Sütun oranı': 'Column ratio',
  'Sığdır': 'Fit',
  'Uzaklaş': 'Zoom out',
  'Varsayılana dön': 'Reset to default',
  'Video dışa aktarma yalnızca masaüstü uygulamasında kullanılabilir (gömülü ffmpeg).': 'Video export is available in the desktop app only (bundled ffmpeg).',
  'Yazarlık kaydı': 'Authorship record',
  'Yukarı': 'Up',
  'Yükle': 'Load',
  'Yükledikten sonra bir satır seç ve': 'After loading, select a line and press',
  'Zaman çizelgesi toplamı:': 'Timeline total:',
  'aç': 'open',
  'değişti': 'changed',
  'hazır': 'ready',
  'kırmızı': 'red',
  'sarı': 'yellow',
  'yaklaşık': 'about',
  'yalnız bu bilgisayar': 'this computer only',
  'yeşil': 'green',
  '· sayfa süreyi ölçmez': '· pages do not measure time',
  'Çevir': 'Translate',
  'Çeviri': 'Translation',
  'Çevriliyor…': 'Translating…',
  'Çözümlenecek senaryo yok.': 'No screenplay to analyse.',
  'Çözümlenecek yapı yok.': 'No structure to analyse.',
  'Özel eşya': 'Special item',
  'Üçler kuralı': 'Rule of thirds',
  'İleri al (Ctrl+Y)': 'Redo (Ctrl+Y)',
  'İletişim (sol alt köşe)': 'Contact (bottom left)',
  'İlk paneli oluştur': 'Create the first panel',
  'İmleç şu an bir satırda değil.': 'The cursor is not on a line right now.',
  'İşaretleme': 'Markup',
  'Şeffaf arka plan (panel zemini çizilmez)': 'Transparent background (the panel ground is not drawn)',
  '↑↓ gez · Enter seç · Esc kapat': '↑↓ browse · Enter select · Esc close',
  'Alt Açı': 'Low Angle',
  'Araç': 'Vehicle',
  'Ayaklı Lamba': 'Floor Lamp',
  'Ayakta (Nötr)': 'Standing (Neutral)',
  'Ağaç': 'Tree',
  'Bağdaş Kurmuş': 'Cross-legged',
  'Baş': 'Head',
  'Bölme': 'Split',
  'Dizüstü Bilgisayar': 'Laptop',
  'Duruş': 'Stance',
  'Dövüş: Gard': 'Fight: Guard',
  'Dövüş: Tekme': 'Fight: Kick',
  'Dövüş: Yumruk': 'Fight: Punch',
  'El Sıkışma': 'Handshake',
  'Elde çekim; titrek, belgesel gerçekçiliği.': 'Handheld; shaky, documentary realism.',
  'Eğik Açı': 'Dutch Angle',
  'Geriye Düşme': 'Falling Backwards',
  'Göz Hizası': 'Eye Level',
  'Hızlı Yürüyüş': 'Brisk Walk',
  'Kapı': 'Door',
  'Kaydırarak Uzaklaşma': 'Dolly Out',
  'Kaydırarak Yaklaşma': 'Dolly In',
  'Kollar Kavuşmuş': 'Arms Folded',
  'Koşma (Adım)': 'Running (Stride)',
  'Koşma (Havada)': 'Running (Airborne)',
  'Kutu Taşıma': 'Carrying a Box',
  'Kuşbakışı': 'Bird\'s Eye',
  'Omuz Kamerası': 'Shoulder Cam',
  'Omuz Üstü': 'Over the Shoulder',
  'Omuzda Taşıma': 'Carrying on Shoulder',
  'Optik Uzaklaşma': 'Zoom Out',
  'Sarılma': 'Embrace',
  'Sağ Ayak': 'Right Foot',
  'Sağ Dirsek': 'Right Elbow',
  'Sağ Diz': 'Right Knee',
  'Sağ El': 'Right Hand',
  'Sağ Kalça': 'Right Hip',
  'Sağ Omuz': 'Right Shoulder',
  'Sokak Lambası': 'Street Lamp',
  'Sol Ayak': 'Left Foot',
  'Sol Dirsek': 'Left Elbow',
  'Sol Diz': 'Left Knee',
  'Sol El': 'Left Hand',
  'Sol Kalça': 'Left Hip',
  'Sol Omuz': 'Left Shoulder',
  'Yukarıyı İşaret': 'Pointing Up',
  'Yürüyüş (Adım)': 'Walking (Stride)',
  'Yürüyüş (Geçiş)': 'Walking (Passing)',
  'Zıplama': 'Jumping',
  'gardırop': 'wardrobe',
  'kapı': 'door',
  'taş': 'stone',
  'yatak odası': 'bedroom',
  'yürüme': 'walking',
  'Çam Ağacı': 'Pine Tree',
  'Çekme': 'Pulling',
  'Çömelme': 'Crouching',
  'Ölçek': 'Scale',
  'Üst Açı': 'High Angle',
  'Üç Çeyrek Açı': 'Three-quarter Angle',
  'çalı': 'bush',
  'çalılık': 'shrubs',
  'çalışma': 'working',
  'çuval': 'sack',
  'İleri Düşme': 'Falling Forwards',
  'İleriyi İşaret Etme': 'Pointing Ahead',
  'İtme': 'Pushing',
  'Bu adres YALNIZ bu bilgisayarda çalışır. Davetli başka bir makinedeyse linki açtığında kendi bilgisayarına gider ve "bağlanamadı" der. Sunucuyu ağdan erişilebilir bir adresle başlat ya da STORYBOARD_WEB_URL ile genel adresi ver.': 'This address works ONLY on this computer. If your guest is on another machine, the link will point at their own computer and say "could not connect". Start the server on an address reachable from the network, or give the public address with STORYBOARD_WEB_URL.',
  'tutuluyor — bu tarihten önce yazılmış satırlar için bilgi yok.': 'is kept — there is no information for lines written before that date.',
  'ile o satıra bağlı panel oluştur.': 'to create a panel linked to that line.',
  ' · sayfa süreyi ölçmez': ' · pages do not measure time',
  '#root bulunamadı': '#root not found',
  '(başlıksız sahne)': '(untitled scene)',
  'API anahtarı gerekli.': 'An API key is required.',
  'Altın oran': 'Golden ratio',
  'Altın spiral': 'Golden spiral',
  'Ayrıntı': 'Detail',
  'Ayrıntıyı gizle': 'Hide detail',
  'Bağlantıyı kaldır (satır kalır)': 'Remove the link (the line stays)',
  'Bu listeyi aç': 'Open this list',
  'Canvas’ı kaydır': 'Pan the canvas',
  'Tam ekran': 'Fullscreen',
  'Tam ekrandan çık': 'Exit fullscreen',
  'Tam ekran açılamadı. Tarayıcı iznini kontrol edin.': 'Could not enter fullscreen. Check browser permissions.',
  'Tam ekrandan çıkılamadı.': 'Could not exit fullscreen.',
  'Orta tuş + sürükle': 'Middle button + drag',
  'Yatay kaydır': 'Pan horizontally',
  'DeepL anahtarı (:fx ücretsiz)': 'DeepL key (:fx is free)',
  'Dünya adı': 'World name',
  'Düzen': 'Layout',
  'En öne': 'To front',
  'Fare tekerleği': 'Mouse wheel',
  'Google API anahtarı': 'Google API key',
  'Grid ↔ pano görünümü': 'Grid ↔ board view',
  'Harmonik üçgen': 'Harmonic triangle',
  'Kim ne yazdı': 'Who wrote what',
  'Kuruluş': 'Organisation',
  'Merkez çapraz': 'Centre diagonal',
  'Odak modundan çık — sonra gizli paneller, sonra seçim': 'Leave focus mode — then hidden panels, then the selection',
  'PDF oluştur (senaryo + storyboard)': 'Create PDF (screenplay + storyboard)',
  'Panele sabitlenmiş (PNG)': 'Flattened into the panel (PNG)',
  'Panelleri gizle / göster': 'Hide / show panels',
  'Satır aralığı seç': 'Choose line spacing',
  'Satıra bağlı çizimi aç': 'Open the drawing linked to the line',
  'Satırlar arasında gez': 'Move between lines',
  'Satırı bir panele bırakarak bağla': 'Link a line by dropping it on a panel',
  'Senaryo bloğu': 'Screenplay block',
  'Senaryo sayfası ↔ pano görünümü': 'Screenplay page ↔ board view',
  'Senaryo yüklenmedi': 'No screenplay loaded',
  'Seçili satırlardan panel oluştur ve bağla': 'Create panels from the selected lines and link them',
  'Seçili satırları açık panele bağla': 'Link the selected lines to the open panel',
  'Sürükle': 'Drag',
  'Temizlenecek eski kayıt yok.': 'No old records to clear.',
  'Yakınlaş': 'Zoom in',
  'Yakınlaştır / uzaklaştır': 'Zoom in / out',
  'atlandı': 'skipped',
  'taşındı': 'moved',
  'yükleniyor': 'loading',
  'Çapraz yöntem': 'Diagonal method',
  'Çevrilecek senaryo yok.': 'No screenplay to translate.',
  'Önceki / sonraki panel': 'Previous / next panel',
  'Önceki / sonraki yer imi': 'Previous / next bookmark',
  'Öne': 'Forward',
  'İmleçteki satıra yer imi koy / kaldır': 'Bookmark / unbookmark the line at the cursor',
  'İmleçteki satırın yazım preseti — aşağıdaki listeye bak': 'The writing preset of the line at the cursor — see the list below',
  'İngilizce': 'English',
  'İspanyolca': 'Spanish',
  'İtalyanca': 'Italian',
  'İÇ - MEKÂN - GÜN': 'INT. LOCATION - DAY',
  'Şablonlar': 'Templates',
  '(nasıl)': '(how)',
  'Davet bağlantısı adres satırında taşınıyor ve tarayıcı geçmişine düşüyor. Sınır, bağlantı sızsa bile yabancının girmesini engelliyor.': 'The invite link travels in the address bar and lands in browser history. The limit stops a stranger getting in even if the link leaks.',
  'en kısa': 'shortest',
  'en uzun': 'longest',
  '+ Panel': '+ Panel',
  '+ Yeni': '+ New',
  '30 günden eski kayıtlar otomatik temizlenir.': 'Records older than 30 days are cleared automatically.',
  'Akademi / klasik TV': 'Academy / classic TV',
  'Anamorfik sinemaskop': 'Anamorphic Cinemascope',
  'Araya ekle': 'Insert here',
  'Açtığın her proje buraya bir kitap olarak gelir. Diskteki bir dosyayı soldan da açabilirsin.': 'Every project you open lands here as a book. You can also open a file from disk on the left.',
  'Açıklaştır': 'Lighten',
  'Açılma (Fade In)': 'Fade In',
  'Bir satırdayken B ile im koy.': 'Press B while on a line to bookmark it.',
  'Bölüm': 'Chapter',
  'Dizi bölümü': 'TV episode',
  'Editör': 'Editor',
  'Ekran': 'Screen',
  'Fark': 'Difference',
  'Fransız (iki sütun)': 'French (two column)',
  'HD / dijital standart': 'HD / digital standard',
  'Her şey + dışa aktarma + davet + rol değiştirme': 'Everything + export + invites + changing roles',
  'Kaplama': 'Overlay',
  'Karakter': 'Character',
  'Karakterler': 'Characters',
  'Kararma (Fade Out)': 'Fade Out',
  'Kare — sosyal medya': 'Square — social media',
  'Kesme (Cut)': 'Cut',
  'Koyulaştır': 'Darken',
  'Lokasyonlar': 'Locations',
  'Normal': 'Normal',
  'Otomatik': 'Automatic',
  'Panel ekle': 'Add panel',
  'Parantez': 'Parenthetical',
  'Perde': 'Act',
  'Radyo oyunu': 'Radio play',
  'Roman': 'Novel',
  'Sahne başlığı': 'Scene heading',
  'Sahne listesi': 'Scene list',
  'Sahne oyunu': 'Stage play',
  'Sahne ritmi': 'Scene rhythm',
  'Salt okunur': 'Read only',
  'Sinema geniş ekran': 'Cinema widescreen',
  'Tam düzenleme, dışa aktarma yok': 'Full editing, no export',
  'Tür ve sayfa düzeni projenin kimliğidir; yazarken değişmez. Sayfa sayısı — ve senaryoda süre — bu seçime dayanıyor.': 'The type and page layout are the project\'s identity; they do not change while you write. The page count — and the running time in a screenplay — rest on this choice.',
  'Yalnızca yorum ve işaretleme katmanı': 'Comments and the markup layer only',
  'Yapı birimi': 'Structural unit',
  'Yer imleri': 'Bookmarks',
  'Yetişkin Erkek': 'Adult Male',
  'Yetişkin Kadın': 'Adult Female',
  'Yorumcu': 'Commenter',
  'bir sayfa ≈ bir dakika': 'one page ≈ one minute',
  'ortalama': 'average',
  'panel': 'panel',
  'proje yaratılırken seçildi': 'chosen when the project was created',
  'sayfa/sahne': 'pages/scene',
  'sn': 's',
  'toplam': 'total',
  'Çarpım': 'Multiply',
  'Çekim dökümü': 'Shot breakdown',
  'Çizgi roman': 'Comic',
  'Çocuk': 'Child',
  'Çözülme (Dissolve)': 'Dissolve',
  'İnce': 'Slim',
  'İri': 'Heavy',
  'İzleyici': 'Viewer',
  '%d günden eski kayıtlar otomatik temizlenir.': 'Records older than %d days are cleared automatically.',
  'dış': 'EXT',
  'iç': 'INT',
  'listesi': 'list',
  'B ile im koy · < > ile gez': 'B to bookmark · < > to move',
  'Doküman tipi': 'Document type',
  'ile im koy.': 'to bookmark it.',
  'Altyazı': 'Subtitle',
  'Balon': 'Balloon',
  'Kare': 'Panel',
  'Müzik': 'Music',
  'Paragraf': 'Paragraph',
  'Sahne yönergesi': 'Stage direction',
  'Ses': 'Sound',
  'Bir satırdayken': 'While on a line, press',
  '3D model yok': 'No 3D model',
  'Hikâye sırası': 'Story order',
  'Zaman': 'Time',
  'geriye dönüş': 'flashback',
  'ileriye sıçrama': 'flash-forward',
  'rüya / hayal': 'dream / vision',
  'şimdi': 'present',
  'Analiz Panosu': 'Analysis Board',
  'GECE': 'NIGHT',
  'Karşılaşma için en az iki karakter gerek.': 'At least two characters are needed to measure encounters.',
  'Kim kiminle': 'Who with whom',
  'Konuşma dengesi': 'Speaking balance',
  'KİŞİ': 'PEOPLE',
  'MEKÂN': 'LOCATIONS',
  'Mekân ekonomisi': 'Location economy',
  'Replik uzunluğu': 'Line length',
  'SAHNE': 'SCENES',
  'Varlık / yokluk': 'Presence / absence',
  'Zaman katmanı': 'Time layer',
  'anlatı düzlemi': 'narrative plane',
  'en uzun görünmeme': 'longest absence',
  'gece kümesi': 'night clusters',
  'her çift en az bir sahne paylaşıyor': 'every pair shares at least one scene',
  'medyan kelime': 'median words',
  'mekân tipi · günün saati': 'interior/exterior · time of day',
  'paylaşılan sahne': 'shared scenes',
  'sayfa payı': 'page share',
  'toplam repliğin payı': 'share of all lines',
  'Çekim koşulları': 'Shooting conditions',
  'çift hiç karşılaşmıyor': 'pairs never meet',
  'Anlatı ↔ hikâye': 'Plot ↔ story',
  'Diyalog ↔ aksiyon': 'Dialogue ↔ action',
  'En az iki sahne gerek.': 'At least two scenes are needed.',
  'Günün saati': 'Time of day',
  'Mekân tipi': 'Location type',
  'akşam': 'dusk',
  'bilinmiyor': 'unspecified',
  'diyalog': 'dialogue',
  'diyalog satır payı': 'share of dialogue lines',
  'etiketlenmemiş — doğrusal görünüyor': 'untagged — reads as linear',
  'gece': 'night',
  'gündüz': 'day',
  'iç / dış': 'interior / exterior',
  'kesikli çizgi = doğrusal': 'dashed line = linear',
  'sahne kaymış': 'scenes out of order',
  'satır yok': 'no lines',
  'çekim yükü': 'shooting load',
  'şafak': 'dawn',
  'Bu ikili hiç aynı sahnede konuşmuyor.': 'These two never speak in the same scene.',
  'Nerede buluşuyorlar': 'Where they meet',
  'senaryonun': 'of the script',
  'yalnız ikisi': 'just the two',
  'Bütün ölçüler — analiz panosu': 'All measures — analysis board',
  'Bu seçimde hiç sahne yok.': 'No scenes in this selection.',
  'Senaryoda nerede': 'Where in the script',
  'günün saati': 'time of day',
  'konuşan yok': 'nobody speaks',
  'konuştuğu sahneler': 'scenes they speak in',
  'mekân': 'location',
  'mekân tipi': 'location type',
  'Kurtar': 'Recover',
  '%d görselin dosyası bulunamadı': '%d image file(s) could not be found',
  'Kurtarınca': 'After recovery',
  'Kütüphanede ara…': 'Search library…',
  'KİM KONUŞUYOR': 'WHO IS SPEAKING',
  'Lütfen görünecek adınızı girin.': 'Please enter your display name.',
  'Markdown metni': 'Markdown text',
  'Mesafe': 'Distance',
  'Metnin ALTINA basılır: kopyayı işaretler, okumayı engellemez.': 'Printed UNDER the text: marks the copy without blocking reading.',
  'Mod': 'Mode',
  'Ne aktarılacak': 'What to export',
  'Ne görüyoruz?': 'What do we see?',
  'Ne söylüyor?': 'What are they saying?',
  'Notlar': 'Notes',
  'Obje': 'Object',
  'Obje Kamerası': 'Object Camera',
  'Oda kodu': 'Room code',
  'Oda kodu ve davet token’ı gerekli. Davet linkini olduğu gibi açın.': 'Room code and invite token are required. Open the invite link as-is.',
  'Onarım uyarısını kapat': 'Dismiss repair warning',
  'Opaklık': 'Opacity',
  'Ortak Çalışma Oturumu': 'Collaboration Session',
  'Oturum başlatıldı. Davet linkini paylaşabilirsiniz.': 'Session started. You can share the invite link.',
  'Oturum kapatıldı. Proje yerelde açık kalmaya devam ediyor.': 'Session closed. The project stays open locally.',
  'Oturuma katıl': 'Join session',
  'PDF (panel ızgarası)': 'PDF (panel grid)',
  'PDF seçenekleri': 'PDF options',
  'PNG dizisi (ZIP)': 'PNG sequence (ZIP)',
  'Panel': 'Panel',
  'Sırala': 'Reorder',
  'Seçili kart yok': 'No card selected',
  'Kart Bilgisi': 'Card details',
  'Çizimi aç': 'Open drawing',
  'Boya': 'Paint',
  'Dolgu rengi': 'Fill color',
  'Saydam': 'Transparent',
  'Saydam dolgu': 'Transparent fill',
  'Silgi boyutu': 'Eraser size',
  'Yumuşatma': 'Smoothing',
  'Son renkler': 'Recent colors',
  'Katmanı taşı': 'Move layer',
  'Katman yok': 'No layer',
  '%d senaryo satırı': '%d screenplay lines',
  '1 senaryo satırı': '1 screenplay line',
  'Panel Bilgisi': 'Panel Info',
  'Paneldeki tüm objeleri seç': 'Select all objects in panel',
  'Paneller çiziliyor…': 'Rendering panels…',
  'Panoya kopyalandı.': 'Copied to clipboard.',
  'Preset': 'Preset',
  'Preset seçilince dolar': 'Filled when a preset is chosen',
  'Proje kaydedildi.': 'Project saved.',
  'Proje sunucudan alınıyor…': 'Fetching project from server…',
  'Proje ve görünüm': 'Project & view',
  'Rehber': 'Guides',
  'Rehberler': 'Guides',
  'Renk': 'Color',
  'Replik…': 'Line…',
  'Rol sunucu tarafından zorunlu kılınır': 'Roles are enforced by the server',
  'Roller': 'Roles',
  'SFX, müzik…': 'SFX, music…',
  'Sabit ölçüler': 'Fixed measures',
  'Sahip': 'Owner',
  'Sahne': 'Scene',
  'Sahnede ne oluyor?': 'What happens in the scene?',
  'Sahneye göre süz': 'Filter by scene',
  'Sayfa': 'Page',
  'Sayfa aralığı': 'Page range',
  'Sayfa rengi': 'Page color',
  'Sağlam kısım kurtarılacak; son birkaç saniye eksik olabilir.': 'The intact part will be recovered; the last few seconds may be missing.',
  'Senaryo PDF oluştur': 'Create screenplay PDF',
  'Senaryo satırları': 'Screenplay lines',
  'Senaryo satırı': 'Screenplay line',
  'Senaryoda ara…': 'Search screenplay…',
  'Senaryodan panel oluşturuldu.': 'Panel created from screenplay.',
  'Senaryoya bağlı': 'Linked to screenplay',
  'Senaryoyu çevir': 'Translate screenplay',
  'Ses / Efekt': 'Sound / FX',
  'Ses dosyası (opsiyonel)': 'Audio file (optional)',
  'Ses sütunundan hesaplandı — sayfa sayısından DEĞİL': 'Computed from the audio column — NOT from page count',
  'Seçili objeleri sil': 'Delete selected objects',
  'Seçilmedi': 'Not selected',
  'Seçimi ve çizim taslağını temizle': 'Clear selection and drawing draft',
  'Seç…': 'Choose…',
  'Solda ne görüyoruz, sağda ne duyuyoruz.': 'Left: what we see. Right: what we hear.',
  'Son Açılan Projeler': 'Recent Projects',
  'Son oturum beklenmedik şekilde kapandı': 'The last session ended unexpectedly',
  'Storyboard PDF oluştur': 'Create storyboard PDF',
  'Storyboard boş — aktarılacak panel yok.': 'Storyboard is empty — no panels to export.',
  'Sunucu adresi': 'Server address',
  'Sunucu değişikliği reddetti': 'Server rejected the change',
  'Sözlüğe eklenecek kelime': 'Word to add to dictionary',
  'Süre': 'Duration',
  'Süreyi sürükleyerek ayarla': 'Drag to adjust duration',
  'Sürüm': 'Version',
  'Sürüm Geçmişi': 'Version History',
  'Sürüm geri yüklendi.': 'Version restored.',
  'Sürüm okunamadı.': 'Could not read version.',
  'Sürüm okunuyor…': 'Reading version…',
  'Sürümler': 'Versions',
  'Sürümleri karşılaştır': 'Compare versions',
  'Tümü': 'All',
  'Tür': 'Type',
  'Uzaklaştır': 'Zoom out',
  'Video kaydedilmedi.': 'Video was not saved.',
  'Video kodlanıyor…': 'Encoding video…',
  'Word belgesi': 'Word document',
  'Word belgesi oluştur': 'Create Word document',
  'Yakınlaştır': 'Zoom in',
  'Yalnız ekranda — dışa aktarım her zaman beyaz sayfaya siyah yazıdır.': 'On-screen only — exports are always black text on a white page.',
  'Yalnız senaryo': 'Screenplay only',
  'Yalnız storyboard': 'Storyboard only',
  'Yapı': 'Structure',
  'Yatay aynala': 'Flip horizontally',
  'Yazılıyor': 'Writing',
  'Yazım': 'Writing',
  'Yenile': 'Refresh',
  'Yer imi': 'Bookmark',
  'Yer imi etiketi': 'Bookmark label',
  'Yer imini kaldır': 'Remove bookmark',
  'Yoksay ve yedeği koru': 'Ignore and keep the backup',
  'Yorum/işaretleme katmanı ekle': 'Add comment/markup layer',
  'Yükleniyor…': 'Loading…',
  'Yükseklik': 'Height',
  'Zaman çizelgesi': 'Timeline',
  'Zemin': 'Background',
  'bekliyor': 'pending',
  'bozuk kayıt': 'corrupt record',
  'bulundu.': 'was found.',
  'güncelleme bu projeye uygulanamadı.': 'update(s) could not be applied to this project.',
  'günlük bekliyor': 'journal waiting',
  'günlüğe işlendi': 'journaled at',
  'kapalı': 'off',
  'karakter': 'characters',
  'kelime': 'words',
  'rolü dışa aktarabilir.': 'role can export.',
  'sayfa': 'pages',
  'sayfa sayısı editördekiyle aynı': 'page count matches the editor',
  'virgülle ayır': 'comma-separated',
  'yarım kalmış yazım': 'an interrupted write',
  'yedek kaydı açılamadı, bir öncekine düşüldü.': 'backup record(s) could not be opened; fell back to an earlier one.',
  'Çekim': 'Shot',
  'Çerçeve Rehberi': 'Frame Guide',
  'Çizim': 'Drawing',
  'Çokgeni kapat': 'Close polygon',
  'Çoğalt (seçim varsa obje, yoksa panel)': 'Duplicate (object if selected, else panel)',
  'Çöp': 'Trash',
  'Çözünürlük': 'Resolution',
  'Ölçek X': 'Scale X',
  'Ölçek Y': 'Scale Y',
  'Ölçü': 'Measure',
  'Ölçülebilir bir değişiklik yok — kurtarma yalnızca küçük düzeltmeler getiriyor olabilir.': 'No measurable difference — the recovery may only contain small corrections.',
  'Özellikler': 'Properties',
  'Özellikler panelini aç': 'Expand Properties panel',
  'Özellikler panelini daralt': 'Collapse Properties panel',
  'Zaman çizelgesi panelini aç': 'Expand Timeline panel',
  'Zaman çizelgesi panelini daralt': 'Collapse Timeline panel',
  'ölçüler aynı, sayfalamayı Word yapar': 'measures match; Word does its own pagination',
  'ör. Ajans adı / telefon / e-posta': 'e.g. agency name / phone / email',
  'İkisi birlikte': 'Both together',
  'İleri al': 'Redo',
  'İmler': 'Marks',
  'İptal et': 'Cancel',
  'İsimsiz': 'Untitled',
  'Şimdi': 'Now',
  /* i18n denetimi 2026-09-25 — İngilizce arayüzde Türkçe kalan bildirim,
     ilerleme, hata, ipucu ve SUNUCU mesajları (sunucu mesajları anahtar olarak
     gelir, collab/api.ts sunucuMetni çevirir). Bulan araçlar:
     tools/i18n-runtime-audit.mjs, tools/i18n-static-audit.mjs. */
  '%d satır bu panele bağlandı.': '%d lines linked to this panel.',
  'Senaryo yüklendi — %d satır.': 'Screenplay loaded — %d lines.',
  'İçe aktarım tam eşleşmedi: %s': 'Import did not match exactly: %s',
  'Senaryo okunamadı: %s': 'Could not read the screenplay: %s',
  '%d/%d bağlı': '%d/%d linked',
  '%s — aç (sağ tık: bağlantıyı kaldır)': '%s — open (right-click: unlink)',
  'az önce': 'just now',
  '%d dakika önce': '%d min ago',
  '%d saat %d dakika önce': '%d h %d min ago',
  '%d saat önce': '%d h ago',
  '%d gün %d saat önce': '%d d %d h ago',
  '%d gün önce': '%d d ago',
  '%d satır geri getirildi.': '%d lines restored.',
  'Seçileni geri getir': 'Restore selected',
  '%d eklendi · %d silindi · %d değişti': '%d added · %d deleted · %d changed',
  '%d taşındı': '%d moved',
  'Rol güncellendi: %s': 'Role updated: %s',
  'Açılamadı: %s': 'Could not open: %s',
  'Panel %d/%d işleniyor…': 'Processing panel %d/%d…',
  'PNG dizisi kaydedildi: %s': 'PNG sequence saved: %s',
  '%d panel ZIP olarak indirildi.': '%d panels downloaded as a ZIP.',
  'Dışa aktarma hatası: %s': 'Export error: %s',
  'Kare verisi çok büyük (~%d MB). Çözünürlüğü düşürün, FPS\'i azaltın ya da geçiş sürelerini kısaltın.': 'Frame data is too large (~%d MB). Lower the resolution, reduce the FPS or shorten the transitions.',
  'Uyarı: kare listesi süresi zaman çizelgesinden %s ms sapıyor.': 'Warning: the frame list is %s ms off the timeline.',
  'Animatik kaydedildi: %s': 'Animatic saved: %s',
  'Video hatası: %s': 'Video error: %s',
  'Kaydedildi: %s': 'Saved: %s',
  '%s indirildi.': '%s downloaded.',
  'Dışa aktarım başarısız: %s': 'Export failed: %s',
  '%d blok Fountain\'da tipini koruyamadı (ilki: %s). Dosya yine de yazıldı.': '%d blocks could not keep their type in Fountain (first: %s). The file was written anyway.',
  'Panel %d/%d çiziliyor…': 'Drawing panel %d/%d…',
  'PDF kuruluyor…': 'Building the PDF…',
  'PDF hatası: %s': 'PDF error: %s',
  '%s oluştur': 'Create %s',
  'PDF belgesi': 'PDF document',
  '%d satır çevrildi.': '%d lines translated.',
  'Açıldı: %s': 'Opened: %s',
  'Geri yüklenemedi: %s': 'Could not restore: %s',
  'Şimdi bu ana dönülsün mü?': 'Go back to this moment now?',
  '%d eski kayıt geri dönüşüm kutusundan temizlendi.': '%d old items cleared from the recycle bin.',
  '%s KALICI olarak silinsin mi? Bu işlem GERİ ALINAMAZ.': 'Delete %s PERMANENTLY? This CANNOT be undone.',
  '(boş %s)': '(empty %s)',
  '"%s" silinsin mi?': 'Delete "%s"?',
  'Seçim (%d obje)': 'Selection (%d objects)',
  'Obje — %s': 'Object — %s',
  '%s kelimesini sözlükten çıkar': 'Remove "%s" from the dictionary',
  'senaryoya bağlı değil': 'not linked to the screenplay',
  '%d satır bağlandı.': '%d lines linked.',
  '%d senaryo satırına bağlı': 'Linked to %d screenplay lines',
  'STARC projesinde senaryo metni yok.': 'This STARC project has no screenplay text.',
  'Senaryoda okunabilir satır bulunamadı.': 'No readable lines were found in the screenplay.',
  '%d kelime · %d diyalog / %d aksiyon': '%d words · %d dialogue / %d action',
  '%d blok · %d kelime': '%d blocks · %d words',
  'Otomatik kayıt başarısız: %s': 'Autosave failed: %s',
  'Sözlük denetleyiciye yüklenemedi: %s': 'Could not load the dictionary into the spell checker: %s',
  '%s okunamadı.': 'Could not read %s.',
  'Geri dönülecek anlar okunamadı.': 'Could not read the moments to go back to.',
  'Bu ana dönüldü — %d görselin dosyası bulunamadı.': 'Went back to this moment — %d image files were not found.',
  'Bu ana dönüldü.': 'Went back to this moment.',
  'Bu an artık yok — liste yenilendi. Şu anki hâlin değişmedi.': 'This moment no longer exists — the list was refreshed. Your current state is unchanged.',
  'Bu ana dönülemedi. Şu anki hâlin değişmedi, güvenle devam edebilirsin.': 'Could not go back to this moment. Your current state is unchanged; you can safely carry on.',
  'Önceki oturumdan %d kayıt bulundu ama hiçbiri uygulanamadı. Günlük silinmedi, arşive alındı: %s.': '%d records from the previous session were found but none could be applied. The journal was not deleted; it was archived: %s.',
  'Önceki oturumdan %d kayıt bulundu ama hiçbiri uygulanamadı. Günlük silinmedi, arşive alındı.': '%d records from the previous session were found but none could be applied. The journal was not deleted; it was archived.',
  'Çökme kurtarma denetimi yapılamadı: %s': 'The crash-recovery check could not run: %s',
  'Önceki oturumun günlüğü arşive alındı: %s': 'The previous session journal was archived: %s',
  'Önceki oturumun günlüğü yerinde duruyor.': 'The previous session journal was left in place.',
  'Kurtarma diske yazılamadı: %s': 'The recovery could not be written to disk: %s',
  'Önceki günlük arşive alındı.': 'The previous journal was archived.',
  'Günlük arşivlenemedi: %s': 'The journal could not be archived: %s',
  '%d yinelenen': '%d duplicate',
  '%d eksik': '%d missing',
  'Belge açılırken %d blok kimliği onarıldı (%s). Metin kaybı yok — onarım yalnız kimliklere dokundu; panel bağları etkilenmiş olabilir. Kaydettiğinde onarım kalıcı olur.': '%d block IDs were repaired while opening the document (%s). No text was lost — the repair touched only IDs; panel links may be affected. Saving makes the repair permanent.',
  'Kare yüklenemedi.': 'A frame could not be loaded.',
  '2D bağlam oluşturulamadı.': 'Could not create a 2D context.',
  'kaydedilmemiş iş yok': 'no unsaved work',
  '%d saat %d dakikalık iş': '%d h %d min of work',
  '%d dakikalık iş': '%d min of work',
  'bir dakikadan kısa iş': 'less than a minute of work',
  'Şu anki hâlinle aynı.': 'Same as your current state.',
  '%d sahne, ~%s sayfa fark': '%d scenes, ~%s pages different',
  '%s %d sn içinde yanıt vermedi': '%s did not respond within %d s',
  'Günlük yazımı': 'Journal write',
  'Çıpa yazımı': 'Anchor write',
  'Sunucuya bağlanılamadı.': 'Could not connect to the server.',
  'Geçersiz .sbp dosyası: project.json bulunamadı.': 'Invalid .sbp file: project.json was not found.',
  'Proje verisi okunamadı.': 'The project data could not be read.',
  '.fdx okumak için tarayıcı ortamı gerekir.': 'Reading .fdx needs a browser environment.',
  'Geçersiz .fdx dosyası.': 'Invalid .fdx file.',
  'STARC belgesi çözümlenemedi: XML bozuk.': 'The STARC document could not be parsed: the XML is corrupt.',
  'Bu bir STARC projesi değil: documents tablosu yok.': 'This is not a STARC project: there is no documents table.',
  'Dosya SQLite değil ya da bozuk: %s': 'The file is not SQLite or is corrupt: %s',
  '%s: metin olmayan yanıt geldi. Çeviri uygulanmadı.': '%s: the response was not text. The translation was not applied.',
  '%s: boş çeviri yanıtı geldi. Çeviri uygulanmadı.': '%s: the translation came back empty. The translation was not applied.',
  'Çeviri iptal edildi. Belgeye dokunulmadı.': 'Translation cancelled. The document was not touched.',
  'DeepL: beklenmeyen yanıt biçimi. Çeviri uygulanmadı.': 'DeepL: unexpected response format. The translation was not applied.',
  'DeepL: beklenmeyen yanıt biçimi (eksik metin). Çeviri uygulanmadı.': 'DeepL: unexpected response format (missing text). The translation was not applied.',
  'Google Translate: beklenmeyen yanıt biçimi. Çeviri uygulanmadı.': 'Google Translate: unexpected response format. The translation was not applied.',
  'Yazı tipi yüklenemedi (%s, %s). PDF üretilemedi.': 'The typeface could not be loaded (%s, %s). The PDF was not produced.',
  'TSA damgayı vermedi (PKIStatus %s)': 'The TSA did not grant the timestamp (PKIStatus %s)',
  'Bu dosya tarayıcı deposunda bulunamadı.': 'This file was not found in browser storage.',
  'Tarayıcı deposu dolu — otomatik kayıt yapılamadı. Projeyi dosya olarak kaydedin.': 'Browser storage is full — autosave failed. Save the project as a file.',
  'Tarayıcı otomatik kaydı': 'Browser autosave',
  'Animatik video dışa aktarma yalnızca masaüstü uygulamasında kullanılabilir (gömülü ffmpeg).': 'Animatic video export is only available in the desktop app (bundled ffmpeg).',
  'IndexedDB açılamadı': 'IndexedDB could not be opened',
  'IndexedDB isteği başarısız': 'IndexedDB request failed',
  'IndexedDB işlemi başarısız': 'IndexedDB transaction failed',
  'IndexedDB işlemi iptal edildi': 'IndexedDB transaction was aborted',
  'Çıpa bulunamadı': 'Anchor not found',
  'Yazdıkların diske kaydedilemiyor: %s. Projeni başka bir yere kaydet — bu pencereyi kapatma.': 'Your writing cannot be saved to disk: %s. Save the project somewhere else — do not close this window.',
  'Toplam %d şablon · %d kamera preseti · %d obje': '%d templates · %d camera presets · %d objects in total',
  '(%s sn) · %d panel. Geçişler kare kare üretilir; çıktı süresi bu değerle ±100 ms içinde eşleşir.': '(%s s) · %d panels. Transitions are rendered frame by frame; the output duration matches this value within ±100 ms.',
  'satır %d': 'line %d',
  'Ortak çalışma oturumuna katılın. Kurulum gerekmez — tarayıcıdan çalışır.': 'Join a collaboration session. Nothing to install — it runs in the browser.',
  'Sunucu hatası (%s)': 'Server error (%s)',
  'Geçersiz e-posta adresi.': 'Invalid email address.',
  'Parola en az %d karakter olmalı.': 'The password must be at least %d characters.',
  'Bu e-posta ile bir hesap zaten var.': 'An account with this email already exists.',
  'E-posta ya da parola hatalı.': 'Wrong email or password.',
  'Yenileme jetonu geçersiz ya da süresi dolmuş.': 'The refresh token is invalid or has expired.',
  'Oturum jetonu geçersiz ya da süresi dolmuş.': 'The session token is invalid or has expired.',
  'Oturum açmak için hesabınıza giriş yapmalısınız.': 'Sign in to your account to start a session.',
  'Oda bulunamadı.': 'Room not found.',
  'Bu işlem için Sahip rolü gerekir.': 'This action requires the Owner role.',
  'Davet oluşturmak için Sahip rolü gerekir.': 'Creating an invite requires the Owner role.',
  'Geçersiz rol.': 'Invalid role.',
  'Yetki yok.': 'Not permitted.',
  'Davet bulunamadı.': 'Invite not found.',
  'Odaya katılmak için hesabınıza giriş yapmalısınız.': 'Sign in to your account to join the room.',
  'Davet geçersiz ya da süresi dolmuş.': 'The invite is invalid or has expired.',
  'Davet iptal edilmiş.': 'The invite has been revoked.',
  'Davetin süresi dolmuş.': 'The invite has expired.',
  'Bu davet bir hesaba bağlı; giriş yapmalısınız.': 'This invite is tied to an account; sign in first.',
  'Bu davet başka bir hesaba gönderilmiş.': 'This invite was sent to a different account.',
  'Bu davet bağlantısı zaten kullanılmış.': 'This invite link has already been used.',
  'Davet token’ı gerekli.': 'An invite token is required.',
  'Bu koda ait oda bulunamadı.': 'No room was found for this code.',
  'Yetkisiz.': 'Unauthorized.',
  'Rol değiştirmek için Sahip rolü gerekir.': 'Changing roles requires the Owner role.',
  'Geçersiz istek.': 'Invalid request.',
  'Kullanıcı bulunamadı.': 'User not found.',
  'Çok fazla deneme. %d saniye sonra tekrar deneyin.': 'Too many attempts. Try again in %d seconds.',
  'İzleyici rolü değişiklik yapamaz.': 'The Viewer role cannot make changes.',
  'Yorumcu rolü yalnızca işaretleme katmanına yazabilir.': 'The Commenter role can only write to the markup layer.',
  'Güncelleme çözümlenemedi: %s': 'The update could not be decoded: %s',
  'Özne çevrenin içinde çok küçük kalır; mekânı tanıtır.': 'The subject is tiny within the surroundings; establishes the place.',
  'Özne tam görünür, çevre baskın. Genel kuruluş çekimi.': 'The subject is fully visible and the surroundings dominate. A general establishing shot.',
  'Özne baştan ayağa çerçeveyi doldurur.': 'The subject fills the frame from head to toe.',
  'Diz üstünden yukarısı — "cowboy shot".': 'From the knees up — the "cowboy shot".',
  'Belden yukarısı; diyalog için standart.': 'From the waist up; the standard for dialogue.',
  'Göğüsten yukarısı; röportaj çerçevesi.': 'From the chest up; the interview frame.',
  'Yüz çerçeveyi doldurur; duygu aktarımı.': 'The face fills the frame; conveys emotion.',
  'Göz, ağız ya da bir detay. Yoğun gerilim.': 'An eye, a mouth or a detail. Intense tension.',
  'Ön plandaki kişinin omzu üzerinden karşıdakine bakış.': 'Looking at the other person over the shoulder of the one in the foreground.',
  'Kamera karakterin gözü olur; izleyici onun yerine bakar.': 'The camera becomes the character\'s eyes; the audience looks in their place.',
  'İki karakter aynı çerçevede; ilişkiyi kurar.': 'Two characters in one frame; establishes their relationship.',
  'Üç karakter aynı çerçevede.': 'Three characters in one frame.',
  'Nesne ya da detayın araya giren yakın çekimi.': 'A cut-in close shot of an object or detail.',
  'Nötr, tarafsız bakış. Kamera özne göz hizasında.': 'A neutral view. The camera is at the subject\'s eye level.',
  'Aşağıdan yukarı bakış; özneyi güçlü ve heybetli gösterir.': 'Looking up at the subject; makes them look strong and imposing.',
  'Yukarıdan aşağı bakış; özneyi küçük ve savunmasız gösterir.': 'Looking down at the subject; makes them look small and vulnerable.',
  'Tam tepeden bakış; olayı harita gibi gösterir.': 'Directly overhead; shows the action like a map.',
  'Yerden tavana bakış; aşırı heybet ve tedirginlik.': 'From the floor up; extreme dominance and unease.',
  'Kamera sabit, gövde yatayda sağa döner.': 'The camera stays in place and pans right.',
  'Kamera sabit, gövde yatayda sola döner.': 'The camera stays in place and pans left.',
  'Kamera sabit, dikeyde yukarı döner.': 'The camera stays in place and tilts up.',
  'Kamera sabit, dikeyde aşağı döner.': 'The camera stays in place and tilts down.',
  'Kamera fiziksel olarak özneye yaklaşır; perspektif değişir.': 'The camera physically moves toward the subject; the perspective changes.',
  'Kamera özneden uzaklaşır; yalnızlık ve açığa çıkarma.': 'The camera moves away from the subject; isolation and reveal.',
  'Kamera özneye paralel hareket ederek onu takip eder.': 'The camera moves parallel to the subject, following it.',
  'Odak uzaklığı artar; kamera yerinde kalır, perspektif sıkışır.': 'The focal length increases; the camera stays in place and the perspective compresses.',
  'Odak uzaklığı azalır; çerçeve genişler.': 'The focal length decreases; the frame widens.',
  'Kamera dikey olarak yükselir; final ve açığa çıkarma hissi.': 'The camera rises vertically; a sense of finale and reveal.',
  'Kamera yukarıdan aşağı iner; sahneye giriş.': 'The camera descends from above; an entry into the scene.',
  'Diyalog — Omuz Üstü': 'Dialogue — Over the Shoulder',
  'Ön planda sırtı dönük figür, karşısında konuşan karakter.': 'A figure with their back to us in the foreground, the speaking character opposite.',
  'Diyalog — İkili Plan': 'Dialogue — Two Shot',
  'Karşılıklı iki karakter, orta plan.': 'Two characters facing each other, medium shot.',
  'Kuruluş — Geniş Plan': 'Establishing — Wide Shot',
  'Mekânı tanıtan uzak plan; küçük figür ve ufuk çizgisi.': 'A long shot that establishes the place; a small figure and the horizon line.',
  'Koşan figür ve hareket yönü oku.': 'A running figure with a direction-of-movement arrow.',
  'Aksiyon — Dövüş': 'Action — Fight',
  'Yumruk atan ve savunan iki figür.': 'Two figures, one punching and one defending.',
  'Yakın Plan — Tepki': 'Close-Up — Reaction',
  'Tek figür, yüz yakın planı çerçevesi.': 'A single figure in a close-up frame.',
  'Düzen — Notlu Çerçeve': 'Layout — Annotated Frame',
  'Alt şeritte aksiyon ve diyalog notu için yer.': 'Space for action and dialogue notes in the bottom strip.',
  'Düzen — Bölünmüş Ekran': 'Layout — Split Screen',
  'Dikey olarak ikiye bölünmüş çerçeve.': 'A frame split vertically in two.',
  'Siyah': 'Black',
  'Sepya': 'Sepia',
  'Gri': 'Grey',
  'Kamera yana yatar; huzursuzluk ve dengesizlik hissi.': 'The camera tilts sideways; a sense of unease and imbalance.',
  'Aksiyon — Kovalamaca': 'Action — Chase',
  'Senaryoda hiç sahne yok.': 'There are no scenes in the screenplay.',
};
